# Stock Image Scraper 📸

scrappe the image and store the data in the excel

In [2]:
# STEP 1:- Importing the required libraries
import time
import requests
import pandas as pd
from tqdm import tqdm
import chromedriver_binary
from bs4 import BeautifulSoup
from selenium import webdriver
from openpyxl import Workbook
import re
import os
import urllib.request
from urllib.parse import urljoin

In [3]:
# STEP :-2:- Setting up the Selenium WebDriver
driver = webdriver.Chrome()
driver.get("https://stock-pictures.netlify.app/")
time.sleep(5)  # Wait for the page to load

The chromedriver version (147.0.7727.57) detected in PATH at c:\Users\Nbinary\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\chromedriver_binary\chromedriver.exe might not be compatible with the detected chrome version (148.0.7778.181); currently, chromedriver 148.0.7778.178 is recommended for chrome 148.*, so it is advised to delete the driver in PATH and retry

In [4]:
# STEP 3:- Scrapping the url
soup = BeautifulSoup(driver.page_source, "html.parser")
image_elements = soup.select('img.source-img[src$=".jpg"]')
print(f"Found {len(image_elements)} images on the page.")

Found 146 images on the page.

We have to extract the image url,name tags,like and comment on each image

In [5]:
# STEP 3:- Scraping the image details
# image url, name tags, likes and comments on each image
image_data = []
for sp in soup.find_all('div', class_='container'):
    img = sp.find('img')
    
    # 1. Safely check if img exists AND has a src attribute before proceeding
    if img and img.get('src') and 'gif' not in img.get('src'):
        link = img.get('src')
        
        # 2. Safely extract tags (Default to empty string if missing)
        tags_div = sp.find('div', class_='tags')
        tags_text = ""
        if tags_div:
            # Assuming the first 7 chars were something like "Tags: "
            # A safer way is replacing the specific word, or just matching words
            raw_tags = tags_div.text[7:].strip().split(' ')
            tags_text = ' '.join(list(set(raw_tags)))
        
        # 3. Safely extract likes and comments (Default to 0 if missing)
        likes, comments = 0, 0
        likes_comments_div = sp.find('div', class_='likes-comments')
        
        if likes_comments_div:
            spans = likes_comments_div.find_all('span')
            
            # re.search(r'\d+', text) finds the first sequence of numbers in a string
            if len(spans) > 0:
                likes_match = re.search(r'\d+', spans[0].text)
                likes = int(likes_match.group()) if likes_match else 0
                
            if len(spans) > 1:
                comments_match = re.search(r'\d+', spans[1].text)
                comments = int(comments_match.group()) if comments_match else 0
        
        image_data.append([link, tags_text, likes, comments])

In [6]:
# STEP 4: Make in to a dataframe
df = pd.DataFrame(image_data, columns=['Image URL', 'Tags', 'Likes', 'Comments'])

In [7]:
df

,Image URL,Tags,Likes,Comments
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Clouds, Blue Sky Atmosphere,",196,55
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Hummingbird Ornithology, Bird,",76,20
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Rainbow, Rainfall, Subtropical Sea,",282,106
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Sakura Road, Cherry Japan, Blossoms,",42,11
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Cape Marguerite, Plant Flower,",39,15
...,...,...,...,...
141,https://cdn.pixabay.com/photo/2022/03/28/20/47...,"Composition, view lake",81,81
142,https://cdn.pixabay.com/photo/2022/04/08/17/33...,"Songbird, Blackbird, Animal Fauna, Bird,",18,11
143,https://cdn.pixabay.com/photo/2022/04/10/10/04...,"riverbanks. and bird, regions it cover to area...",10,6
144,https://cdn.pixabay.com/photo/2021/11/09/07/29...,"Newborn, Sleeping Baby, Costume,",91,21
145,https://cdn.pixabay.com/photo/2022/04/02/20/46...,"Backyard, Kitten Cat, Outdoors, Grass,",54,36

In [8]:
# STEP 5: Close the Selenium WebDriver
driver.quit()

In [9]:
# STEP 6: Save the data to an Excel file
df.to_excel("stock_images_data.xlsx", index=False)

In [10]:
# STEP 7: Download the images to a local folder
# Create a folder to save the images
path=[]
os.makedirs("downloaded_images", exist_ok=True)
# Use a browser-like User-Agent to avoid being blocked by the server
download_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}
# Download each image
for index, row in tqdm(df.iterrows(), total=len(df)):
    image_url = row['Image URL']
    if image_url.startswith('/'):
        image_url = urljoin("https://stock-pictures.netlify.app/", image_url)
    image_name = f"image_{index + 1}.jpg"
    save_path = os.path.join("downloaded_images", image_name)
    path.append(save_path)
    try:
        response = requests.get(image_url, headers=download_headers, timeout=30, stream=True)
        response.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=10240):
                if chunk:
                    f.write(chunk)
        print(f"Downloaded: {image_name}")
    except Exception as e:
        print(f"Failed to download {image_name}: {image_url} : {e}")

  0%|          | 0/146 [00:00<?, ?it/s]

  1%|          | 1/146 [00:00<01:22,  1.76it/s]

Downloaded: image_1.jpg

  1%|▏         | 2/146 [00:01<01:21,  1.77it/s]

Downloaded: image_2.jpg

  2%|▏         | 3/146 [00:01<01:19,  1.81it/s]

Downloaded: image_3.jpg

  3%|▎         | 4/146 [00:02<01:19,  1.78it/s]

Downloaded: image_4.jpg

  3%|▎         | 5/146 [00:02<01:17,  1.82it/s]

Downloaded: image_5.jpg

  4%|▍         | 6/146 [00:03<01:17,  1.80it/s]

Downloaded: image_6.jpg

  5%|▍         | 7/146 [00:03<01:17,  1.79it/s]

Downloaded: image_7.jpg

  5%|▌         | 8/146 [00:04<01:16,  1.80it/s]

Downloaded: image_8.jpg

  6%|▌         | 9/146 [00:05<01:17,  1.77it/s]

Downloaded: image_9.jpg

  7%|▋         | 10/146 [00:05<01:16,  1.78it/s]

Downloaded: image_10.jpg

  8%|▊         | 11/146 [00:06<01:15,  1.79it/s]

Downloaded: image_11.jpg

  8%|▊         | 12/146 [00:06<01:14,  1.81it/s]

Downloaded: image_12.jpg

  9%|▉         | 13/146 [00:07<01:13,  1.80it/s]

Downloaded: image_13.jpg

 10%|▉         | 14/146 [00:07<01:13,  1.79it/s]

Downloaded: image_14.jpg

 10%|█         | 15/146 [00:08<01:13,  1.79it/s]

Downloaded: image_15.jpg

 11%|█         | 16/146 [00:08<01:12,  1.79it/s]

Downloaded: image_16.jpg

 12%|█▏        | 17/146 [00:10<01:35,  1.34it/s]

Downloaded: image_17.jpg

 12%|█▏        | 18/146 [00:10<01:28,  1.45it/s]

Downloaded: image_18.jpg

 13%|█▎        | 19/146 [00:11<01:22,  1.55it/s]

Downloaded: image_19.jpg

 14%|█▎        | 20/146 [00:11<01:17,  1.62it/s]

Downloaded: image_20.jpg

 14%|█▍        | 21/146 [00:12<01:15,  1.66it/s]

Downloaded: image_21.jpg

 15%|█▌        | 22/146 [00:12<01:13,  1.69it/s]

Downloaded: image_22.jpg

 16%|█▌        | 23/146 [00:13<01:11,  1.72it/s]

Downloaded: image_23.jpg

 16%|█▋        | 24/146 [00:13<01:09,  1.76it/s]

Downloaded: image_24.jpg

 17%|█▋        | 25/146 [00:14<01:07,  1.80it/s]

Downloaded: image_25.jpg

 18%|█▊        | 26/146 [00:15<01:06,  1.79it/s]

Downloaded: image_26.jpg

 18%|█▊        | 27/146 [00:15<01:05,  1.82it/s]

Downloaded: image_27.jpg

 19%|█▉        | 28/146 [00:16<01:04,  1.84it/s]

Downloaded: image_28.jpg

 20%|█▉        | 29/146 [00:16<01:03,  1.83it/s]

Downloaded: image_29.jpg

 21%|██        | 30/146 [00:17<01:03,  1.82it/s]

Downloaded: image_30.jpg

 21%|██        | 31/146 [00:17<01:03,  1.82it/s]

Downloaded: image_31.jpg

 22%|██▏       | 32/146 [00:19<01:25,  1.34it/s]

Failed to download image_32.jpg: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg : 403 Client Error: Forbidden for url: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg

 23%|██▎       | 33/146 [00:19<01:18,  1.44it/s]

Downloaded: image_33.jpg

 23%|██▎       | 34/146 [00:20<01:13,  1.53it/s]

Downloaded: image_34.jpg

 24%|██▍       | 35/146 [00:20<01:09,  1.60it/s]

Downloaded: image_35.jpg

 25%|██▍       | 36/146 [00:21<01:06,  1.66it/s]

Downloaded: image_36.jpg

 25%|██▌       | 37/146 [00:21<01:04,  1.70it/s]

Downloaded: image_37.jpg

 26%|██▌       | 38/146 [00:22<01:02,  1.72it/s]

Downloaded: image_38.jpg

 27%|██▋       | 39/146 [00:22<01:01,  1.73it/s]

Downloaded: image_39.jpg

 27%|██▋       | 40/146 [00:23<01:00,  1.76it/s]

Downloaded: image_40.jpg

 28%|██▊       | 41/146 [00:24<00:59,  1.78it/s]

Downloaded: image_41.jpg

 29%|██▉       | 42/146 [00:24<00:59,  1.75it/s]

Downloaded: image_42.jpg

 29%|██▉       | 43/146 [00:25<00:58,  1.76it/s]

Downloaded: image_43.jpg

 30%|███       | 44/146 [00:25<00:57,  1.77it/s]

Downloaded: image_44.jpg

 31%|███       | 45/146 [00:26<00:56,  1.78it/s]

Downloaded: image_45.jpg

 32%|███▏      | 46/146 [00:26<00:56,  1.77it/s]

Downloaded: image_46.jpg

 32%|███▏      | 47/146 [00:27<00:56,  1.74it/s]

Downloaded: image_47.jpg

 33%|███▎      | 48/146 [00:28<00:55,  1.77it/s]

Downloaded: image_48.jpg

 34%|███▎      | 49/146 [00:28<00:54,  1.76it/s]

Downloaded: image_49.jpg

 34%|███▍      | 50/146 [00:29<00:54,  1.75it/s]

Downloaded: image_50.jpg

 35%|███▍      | 51/146 [00:29<00:53,  1.76it/s]

Downloaded: image_51.jpg

 36%|███▌      | 52/146 [00:30<00:53,  1.75it/s]

Downloaded: image_52.jpg

 36%|███▋      | 53/146 [00:30<00:53,  1.75it/s]

Downloaded: image_53.jpg

 37%|███▋      | 54/146 [00:31<00:52,  1.75it/s]

Downloaded: image_54.jpg

 38%|███▊      | 55/146 [00:31<00:51,  1.76it/s]

Downloaded: image_55.jpg

 38%|███▊      | 56/146 [00:32<00:50,  1.78it/s]

Downloaded: image_56.jpg

 39%|███▉      | 57/146 [00:33<00:50,  1.77it/s]

Downloaded: image_57.jpg

 40%|███▉      | 58/146 [00:33<00:49,  1.78it/s]

Downloaded: image_58.jpg

 40%|████      | 59/146 [00:34<00:48,  1.79it/s]

Downloaded: image_59.jpg

 41%|████      | 60/146 [00:34<00:47,  1.81it/s]

Downloaded: image_60.jpg

 42%|████▏     | 61/146 [00:35<00:46,  1.81it/s]

Downloaded: image_61.jpg

 42%|████▏     | 62/146 [00:35<00:46,  1.79it/s]

Downloaded: image_62.jpg

 43%|████▎     | 63/146 [00:36<00:46,  1.78it/s]

Downloaded: image_63.jpg

 44%|████▍     | 64/146 [00:37<00:46,  1.77it/s]

Downloaded: image_64.jpg

 45%|████▍     | 65/146 [00:37<00:46,  1.75it/s]

Downloaded: image_65.jpg

 45%|████▌     | 66/146 [00:38<00:45,  1.77it/s]

Downloaded: image_66.jpg

 46%|████▌     | 67/146 [00:38<00:45,  1.75it/s]

Downloaded: image_67.jpg

 47%|████▋     | 68/146 [00:39<00:44,  1.75it/s]

Downloaded: image_68.jpg

 47%|████▋     | 69/146 [00:39<00:44,  1.74it/s]

Downloaded: image_69.jpg

 48%|████▊     | 70/146 [00:40<00:43,  1.74it/s]

Downloaded: image_70.jpg

 49%|████▊     | 71/146 [00:41<00:42,  1.77it/s]

Downloaded: image_71.jpg

 49%|████▉     | 72/146 [00:41<00:41,  1.79it/s]

Downloaded: image_72.jpg

 50%|█████     | 73/146 [00:42<00:40,  1.78it/s]

Downloaded: image_73.jpg

 51%|█████     | 74/146 [00:42<00:40,  1.76it/s]

Downloaded: image_74.jpg

 51%|█████▏    | 75/146 [00:43<00:40,  1.76it/s]

Downloaded: image_75.jpg

 52%|█████▏    | 76/146 [00:43<00:39,  1.78it/s]

Downloaded: image_76.jpg

 53%|█████▎    | 77/146 [00:44<00:38,  1.80it/s]

Downloaded: image_77.jpg

 53%|█████▎    | 78/146 [00:44<00:38,  1.78it/s]

Downloaded: image_78.jpg

 54%|█████▍    | 79/146 [00:45<00:37,  1.80it/s]

Downloaded: image_79.jpg

 55%|█████▍    | 80/146 [00:46<00:36,  1.81it/s]

Downloaded: image_80.jpg

 55%|█████▌    | 81/146 [00:46<00:35,  1.81it/s]

Downloaded: image_81.jpg

 56%|█████▌    | 82/146 [00:47<00:35,  1.81it/s]

Downloaded: image_82.jpg

 57%|█████▋    | 83/146 [00:47<00:35,  1.79it/s]

Downloaded: image_83.jpg

 58%|█████▊    | 84/146 [00:48<00:34,  1.79it/s]

Downloaded: image_84.jpg

 58%|█████▊    | 85/146 [00:48<00:34,  1.79it/s]

Downloaded: image_85.jpg

 59%|█████▉    | 86/146 [00:49<00:33,  1.79it/s]

Downloaded: image_86.jpg

 60%|█████▉    | 87/146 [00:49<00:32,  1.79it/s]

Downloaded: image_87.jpg

 60%|██████    | 88/146 [00:50<00:33,  1.75it/s]

Downloaded: image_88.jpg

 61%|██████    | 89/146 [00:51<00:32,  1.75it/s]

Downloaded: image_89.jpg

 62%|██████▏   | 90/146 [00:51<00:32,  1.73it/s]

Downloaded: image_90.jpg

 62%|██████▏   | 91/146 [00:52<00:31,  1.74it/s]

Downloaded: image_91.jpg

 63%|██████▎   | 92/146 [00:52<00:30,  1.77it/s]

Downloaded: image_92.jpg

 64%|██████▎   | 93/146 [00:53<00:29,  1.80it/s]

Downloaded: image_93.jpg

 64%|██████▍   | 94/146 [00:53<00:29,  1.79it/s]

Downloaded: image_94.jpg

 65%|██████▌   | 95/146 [00:54<00:28,  1.78it/s]

Downloaded: image_95.jpg

 66%|██████▌   | 96/146 [00:55<00:28,  1.74it/s]

Downloaded: image_96.jpg

 66%|██████▋   | 97/146 [00:55<00:27,  1.76it/s]

Downloaded: image_97.jpg

 67%|██████▋   | 98/146 [00:56<00:27,  1.77it/s]

Downloaded: image_98.jpg

 68%|██████▊   | 99/146 [00:56<00:26,  1.78it/s]

Downloaded: image_99.jpg

 68%|██████▊   | 100/146 [00:57<00:25,  1.78it/s]

Downloaded: image_100.jpg

 69%|██████▉   | 101/146 [00:57<00:25,  1.79it/s]

Downloaded: image_101.jpg

 70%|██████▉   | 102/146 [00:58<00:24,  1.79it/s]

Downloaded: image_102.jpg

 71%|███████   | 103/146 [00:58<00:23,  1.80it/s]

Downloaded: image_103.jpg

 71%|███████   | 104/146 [00:59<00:23,  1.79it/s]

Downloaded: image_104.jpg

 72%|███████▏  | 105/146 [01:00<00:22,  1.79it/s]

Downloaded: image_105.jpg

 73%|███████▎  | 106/146 [01:00<00:22,  1.77it/s]

Downloaded: image_106.jpg

 73%|███████▎  | 107/146 [01:01<00:21,  1.80it/s]

Downloaded: image_107.jpg

 74%|███████▍  | 108/146 [01:01<00:20,  1.81it/s]

Downloaded: image_108.jpg

 75%|███████▍  | 109/146 [01:02<00:20,  1.81it/s]

Downloaded: image_109.jpg

 75%|███████▌  | 110/146 [01:02<00:20,  1.79it/s]

Downloaded: image_110.jpg

 76%|███████▌  | 111/146 [01:03<00:19,  1.78it/s]

Downloaded: image_111.jpg

 77%|███████▋  | 112/146 [01:03<00:18,  1.80it/s]

Downloaded: image_112.jpg

 77%|███████▋  | 113/146 [01:04<00:18,  1.80it/s]

Downloaded: image_113.jpg

 78%|███████▊  | 114/146 [01:05<00:17,  1.78it/s]

Downloaded: image_114.jpg

 79%|███████▉  | 115/146 [01:05<00:17,  1.79it/s]

Downloaded: image_115.jpg

 79%|███████▉  | 116/146 [01:06<00:16,  1.77it/s]

Downloaded: image_116.jpg

 80%|████████  | 117/146 [01:06<00:16,  1.77it/s]

Downloaded: image_117.jpg

 81%|████████  | 118/146 [01:07<00:16,  1.75it/s]

Downloaded: image_118.jpg

 82%|████████▏ | 119/146 [01:07<00:15,  1.75it/s]

Downloaded: image_119.jpg

 82%|████████▏ | 120/146 [01:08<00:14,  1.75it/s]

Downloaded: image_120.jpg

 83%|████████▎ | 121/146 [01:09<00:14,  1.76it/s]

Downloaded: image_121.jpg

 84%|████████▎ | 122/146 [01:10<00:18,  1.28it/s]

Downloaded: image_122.jpg

 84%|████████▍ | 123/146 [01:11<00:16,  1.37it/s]

Downloaded: image_123.jpg

 85%|████████▍ | 124/146 [01:11<00:15,  1.46it/s]

Downloaded: image_124.jpg

 86%|████████▌ | 125/146 [01:12<00:13,  1.52it/s]

Downloaded: image_125.jpg

 86%|████████▋ | 126/146 [01:12<00:12,  1.60it/s]

Downloaded: image_126.jpg

 87%|████████▋ | 127/146 [01:13<00:11,  1.65it/s]

Downloaded: image_127.jpg

 88%|████████▊ | 128/146 [01:13<00:10,  1.66it/s]

Downloaded: image_128.jpg

 88%|████████▊ | 129/146 [01:14<00:10,  1.59it/s]

Downloaded: image_129.jpg

 89%|████████▉ | 130/146 [01:15<00:09,  1.62it/s]

Downloaded: image_130.jpg

 90%|████████▉ | 131/146 [01:15<00:08,  1.67it/s]

Downloaded: image_131.jpg

 90%|█████████ | 132/146 [01:16<00:08,  1.70it/s]

Downloaded: image_132.jpg

 91%|█████████ | 133/146 [01:16<00:07,  1.73it/s]

Downloaded: image_133.jpg

 92%|█████████▏| 134/146 [01:17<00:07,  1.68it/s]

Downloaded: image_134.jpg

 92%|█████████▏| 135/146 [01:18<00:06,  1.66it/s]

Downloaded: image_135.jpg

 93%|█████████▎| 136/146 [01:18<00:05,  1.68it/s]

Downloaded: image_136.jpg

 94%|█████████▍| 137/146 [01:19<00:05,  1.68it/s]

Downloaded: image_137.jpg

 95%|█████████▍| 138/146 [01:19<00:04,  1.69it/s]

Downloaded: image_138.jpg

 95%|█████████▌| 139/146 [01:20<00:04,  1.70it/s]

Downloaded: image_139.jpg

 96%|█████████▌| 140/146 [01:20<00:03,  1.72it/s]

Downloaded: image_140.jpg

 97%|█████████▋| 141/146 [01:21<00:02,  1.73it/s]

Downloaded: image_141.jpg

 97%|█████████▋| 142/146 [01:22<00:03,  1.26it/s]

Downloaded: image_142.jpg

 98%|█████████▊| 143/146 [01:23<00:02,  1.37it/s]

Downloaded: image_143.jpg

 99%|█████████▊| 144/146 [01:24<00:01,  1.47it/s]

Downloaded: image_144.jpg

 99%|█████████▉| 145/146 [01:24<00:00,  1.52it/s]

Downloaded: image_145.jpg

100%|██████████| 146/146 [01:25<00:00,  1.71it/s]

Downloaded: image_146.jpg

In [13]:
# STEP 8: Update the Excel file with the local image paths
df['Local Image Path'] = path
df.to_excel("stock_images_data.xlsx", index=False)

In [14]:
df

,Image URL,Tags,Likes,Comments,Local Image Path
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Clouds, Blue Sky Atmosphere,",196,55,downloaded_images\image_1.jpg
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Hummingbird Ornithology, Bird,",76,20,downloaded_images\image_2.jpg
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Rainbow, Rainfall, Subtropical Sea,",282,106,downloaded_images\image_3.jpg
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Sakura Road, Cherry Japan, Blossoms,",42,11,downloaded_images\image_4.jpg
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Cape Marguerite, Plant Flower,",39,15,downloaded_images\image_5.jpg
...,...,...,...,...,...
141,https://cdn.pixabay.com/photo/2022/03/28/20/47...,"Composition, view lake",81,81,downloaded_images\image_142.jpg
142,https://cdn.pixabay.com/photo/2022/04/08/17/33...,"Songbird, Blackbird, Animal Fauna, Bird,",18,11,downloaded_images\image_143.jpg
143,https://cdn.pixabay.com/photo/2022/04/10/10/04...,"riverbanks. and bird, regions it cover to area...",10,6,downloaded_images\image_144.jpg
144,https://cdn.pixabay.com/photo/2021/11/09/07/29...,"Newborn, Sleeping Baby, Costume,",91,21,downloaded_images\image_145.jpg
145,https://cdn.pixabay.com/photo/2022/04/02/20/46...,"Backyard, Kitten Cat, Outdoors, Grass,",54,36,downloaded_images\image_146.jpg