# Stock Image Scraper 📸

scrappe the image and store the data in the excel

In [3]:
# STEP 1:- Importing the required libraries
import time
import requests
import pandas as pd
from tqdm import tqdm
import chromedriver_binary
from bs4 import BeautifulSoup
from selenium import webdriver
from openpyxl import Workbook
import re
import os
import urllib.request
from urllib.parse import urljoin
import shutil

In [4]:
# STEP :-2:- Setting up the Selenium WebDriver
driver = webdriver.Chrome()
driver.get("https://stock-pictures.netlify.app/")
time.sleep(5)  # Wait for the page to load

The chromedriver version (147.0.7727.57) detected in PATH at c:\Users\Nbinary\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\chromedriver_binary\chromedriver.exe might not be compatible with the detected chrome version (148.0.7778.181); currently, chromedriver 148.0.7778.178 is recommended for chrome 148.*, so it is advised to delete the driver in PATH and retry

In [5]:
# STEP 3:- Scrapping the url
soup = BeautifulSoup(driver.page_source, "html.parser")
image_elements = soup.select('img.source-img[src$=".jpg"]')
print(f"Found {len(image_elements)} images on the page.")

Found 48 images on the page.

We have to extract the image url,name tags,like and comment on each image

In [6]:
# STEP 3:- Scraping the image details
# image url, name tags, likes and comments on each image
image_data = []
for sp in soup.find_all('div', class_='container'):
    img = sp.find('img')
    
    # 1. Safely check if img exists AND has a src attribute before proceeding
    if img and img.get('src') and 'gif' not in img.get('src'):
        link = img.get('src')
        
        # 2. Safely extract tags (Default to empty string if missing)
        tags_div = sp.find('div', class_='tags')
        tags_text = ""
        if tags_div:
            # Assuming the first 7 chars were something like "Tags: "
            # A safer way is replacing the specific word, or just matching words
            raw_tags = tags_div.text[7:].strip().split(' ')
            tags_text = ' '.join(list(set(raw_tags)))
        
        # 3. Safely extract likes and comments (Default to 0 if missing)
        likes, comments = 0, 0
        likes_comments_div = sp.find('div', class_='likes-comments')
        
        if likes_comments_div:
            spans = likes_comments_div.find_all('span')
            
            # re.search(r'\d+', text) finds the first sequence of numbers in a string
            if len(spans) > 0:
                likes_match = re.search(r'\d+', spans[0].text)
                likes = int(likes_match.group()) if likes_match else 0
                
            if len(spans) > 1:
                comments_match = re.search(r'\d+', spans[1].text)
                comments = int(comments_match.group()) if comments_match else 0
        
        image_data.append([link, tags_text, likes, comments])

In [7]:
# STEP 4: Make in to a dataframe
df = pd.DataFrame(image_data, columns=['Image URL', 'Tags', 'Likes', 'Comments'])

In [8]:
df

,Image URL,Tags,Likes,Comments
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Sky Clouds, Blue Atmosphere,",196,55
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Ornithology, Hummingbird Bird,",76,20
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainbow, Rainfall, Sea,",282,106
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Road, Sakura Japan, Cherry Blossoms,",42,11
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Marguerite, Cape Plant Flower,",39,15
5,https://cdn.pixabay.com/photo/2021/11/13/23/06...,Tree Relaxing Under Rest The,522,108
6,https://cdn.pixabay.com/photo/2022/04/07/02/56...,"Rabbit, Cottontail Wild Grass",51,10
7,https://cdn.pixabay.com/photo/2022/03/19/21/11...,"Crocus, Flowers, Plant Spring,",135,44
8,https://cdn.pixabay.com/photo/2022/04/09/17/30...,"Drink, Coffee, Vacation, Café, Table",26,5
9,https://cdn.pixabay.com/photo/2022/03/25/19/24...,"Fall, Epic, Nature, Light Waterfall,",96,21
10,https://cdn.pixabay.com/photo/2021/08/25/20/42...,"Nature Field, Sunrise, Dawn, Morning,",807,131
11,https://cdn.pixabay.com/photo/2022/04/04/18/03...,"Robin, Birdwatching, Bird, Animal",69,19
12,https://cdn.pixabay.com/photo/2022/04/04/07/58...,"Spring Soil, Bloom Flowers, Seedlings,",42,9
13,https://cdn.pixabay.com/photo/2022/03/23/21/27...,"Hills Road, Countryside, Highway,",53,14
14,https://cdn.pixabay.com/photo/2022/03/27/15/03...,"Monochrome, Cityscape, City Bridge,",45,13
15,https://cdn.pixabay.com/photo/2022/03/25/17/54...,"Water Spring, Sakura, Cherry Blossoms,",70,12
16,https://cdn.pixabay.com/photo/2022/04/01/19/03...,"Eggs, Template, Background, Art Easter,",5,2
17,https://cdn.pixabay.com/photo/2022/01/31/12/46...,"Indian Species Ornithology, Chat, Bird,",171,53
18,https://cdn.pixabay.com/photo/2022/01/18/16/49...,"Night, Village, Winter, Season Town,",109,15
19,https://cdn.pixabay.com/photo/2022/04/09/17/42...,"Bloom Flower, Pansy, Viola, Blossom,",55,36
20,https://cdn.pixabay.com/photo/2021/08/30/21/29...,"Architecture, Lake, Port, Vacations",276,49
21,https://cdn.pixabay.com/photo/2022/03/16/02/03...,"Flowers, Sunflowers, Plant",54,21
22,https://cdn.pixabay.com/photo/2022/03/28/18/41...,"Spring, Coffee, Flowers, Morning",40,10
23,https://cdn.pixabay.com/photo/2022/02/12/06/21...,"Lake, Peak, Roys Mountains Wanaka,",69,19
24,https://cdn.pixabay.com/photo/2021/11/21/21/14...,"Thank many downloads and you, likes. for every...",197,0
25,https://cdn.pixabay.com/photo/2021/08/22/15/48...,"Exploration Beach, Outdoors, Nature,",272,150
26,https://cdn.pixabay.com/photo/2022/03/03/11/18...,West Danish Jutland. during Shot Coast of suns...,48,11
27,https://cdn.pixabay.com/photo/2022/03/16/21/01...,"Bird, Penguin, Animal Gentoo",93,22
28,https://cdn.pixabay.com/photo/2021/11/26/20/45...,"Sea, Water, Tree Lantern, Heaven, Beach,",243,31
29,https://cdn.pixabay.com/photo/2022/04/03/05/03...,"Spring, Easter, Easter Bunny",17,10
30,https://cdn.pixabay.com/photo/2018/01/14/23/12...,on green rock during brown lake daytime trees ...,3098,495
31,https://cdn.pixabay.com/photo/2022/02/27/19/46...,"Tower, Eiffel Tourist Attraction, Travel",83,21
32,https://cdn.pixabay.com/photo/2022/04/07/22/23...,"Standing Stones, Menhir, Clouds, Stones",64,49
33,https://cdn.pixabay.com/photo/2022/01/13/18/05...,"Path Road, Winter, Snow, Trees, Frost,",133,24
34,https://cdn.pixabay.com/photo/2022/04/10/07/03...,"Bird, Woodpecker",28,20
35,https://cdn.pixabay.com/photo/2021/11/25/19/50...,"Tape, Cassette, Classic Retro, Music,",134,20
36,https://cdn.pixabay.com/photo/2022/01/10/15/29...,"Power Energy, Clouds, Wind Mills,",144,101
37,https://cdn.pixabay.com/photo/2022/02/15/07/27...,"Tartini, Travel, Square, Tourism, Piran",70,19
38,https://cdn.pixabay.com/photo/2022/04/11/04/33...,"Eggs, Nest, Colored Eggs Easter",29,0
39,https://cdn.pixabay.com/photo/2022/02/07/22/27...,"Nature, Winter, Season, Travel Outdoors,",111,24
40,https://cdn.pixabay.com/photo/2022/04/11/09/40...,"Glacier, Dying Glacier Glaciers, Melting",36,27
41,https://cdn.pixabay.com/photo/2021/11/01/21/31...,"Jungle, Nature Tropical, Green, Forest,",135,22
42,https://cdn.pixabay.com/photo/2022/02/05/08/13...,"Flower, Tulip, Petals Bloom, Blossom,",92,35
43,https://cdn.pixabay.com/photo/2022/04/07/13/06...,"Flowers, Petals Pink",62,0
44,https://cdn.pixabay.com/photo/2022/02/22/03/22...,"Passiflora, Flower, Passion Flower",97,66
45,https://cdn.pixabay.com/photo/2021/11/02/21/57...,"Blessing Faith, Prayer, Hope, Religion,",175,57
46,https://cdn.pixabay.com/photo/2022/04/09/10/13...,"Star, Cosmos Space, Universe, Galaxy,",45,40
47,https://cdn.pixabay.com/photo/2022/03/31/09/25...,"Macro Insect, Dragonfly, Nature,",19,3

In [9]:
# STEP 5: Close the Selenium WebDriver
driver.quit()

In [10]:
# STEP 6: Save the data to an Excel file
df.to_excel("stock_images_data.xlsx", index=False)

In [11]:
# STEP 7: Download the images to a local folder
# Create a folder to save the images
path=[]
os.makedirs("downloaded_images", exist_ok=True)
# Use a browser-like User-Agent to avoid being blocked by the server
download_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}
# Download each image
for index, row in tqdm(df.iterrows(), total=len(df)):
    image_url = row['Image URL']
    if image_url.startswith('/'):
        image_url = urljoin("https://stock-pictures.netlify.app/", image_url)
    image_name = f"image_{index + 1}.jpg"
    save_path = os.path.join("downloaded_images", image_name)
    path.append(save_path)
    try:
        response = requests.get(image_url, headers=download_headers, timeout=30, stream=True)
        response.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=10240):
                if chunk:
                    f.write(chunk)
        print(f"Downloaded: {image_name}")
    except Exception as e:
        print(f"Failed to download {image_name}: {image_url} : {e}")

  0%|          | 0/48 [00:00<?, ?it/s]

  2%|▏         | 1/48 [00:00<00:26,  1.76it/s]

Downloaded: image_1.jpg

  4%|▍         | 2/48 [00:01<00:25,  1.80it/s]

Downloaded: image_2.jpg

  6%|▋         | 3/48 [00:01<00:25,  1.77it/s]

Downloaded: image_3.jpg

  8%|▊         | 4/48 [00:02<00:25,  1.76it/s]

Downloaded: image_4.jpg

 10%|█         | 5/48 [00:02<00:24,  1.74it/s]

Downloaded: image_5.jpg

 12%|█▎        | 6/48 [00:03<00:24,  1.72it/s]

Downloaded: image_6.jpg

 15%|█▍        | 7/48 [00:04<00:24,  1.67it/s]

Downloaded: image_7.jpg

 17%|█▋        | 8/48 [00:04<00:24,  1.62it/s]

Downloaded: image_8.jpg

 19%|█▉        | 9/48 [00:05<00:24,  1.58it/s]

Downloaded: image_9.jpg

 21%|██        | 10/48 [00:06<00:24,  1.54it/s]

Downloaded: image_10.jpg

 23%|██▎       | 11/48 [00:06<00:26,  1.40it/s]

Downloaded: image_11.jpg

 25%|██▌       | 12/48 [00:07<00:26,  1.33it/s]

Downloaded: image_12.jpg

 27%|██▋       | 13/48 [00:08<00:27,  1.27it/s]

Downloaded: image_13.jpg

 29%|██▉       | 14/48 [00:09<00:28,  1.21it/s]

Downloaded: image_14.jpg

 31%|███▏      | 15/48 [00:10<00:28,  1.18it/s]

Downloaded: image_15.jpg

 33%|███▎      | 16/48 [00:11<00:27,  1.16it/s]

Downloaded: image_16.jpg

 35%|███▌      | 17/48 [00:13<00:34,  1.11s/it]

Downloaded: image_17.jpg

 38%|███▊      | 18/48 [00:13<00:29,  1.02it/s]

Downloaded: image_18.jpg

 40%|███▉      | 19/48 [00:14<00:25,  1.12it/s]

Downloaded: image_19.jpg

 42%|████▏     | 20/48 [00:15<00:23,  1.17it/s]

Downloaded: image_20.jpg

 44%|████▍     | 21/48 [00:15<00:21,  1.26it/s]

Downloaded: image_21.jpg

 46%|████▌     | 22/48 [00:16<00:19,  1.32it/s]

Downloaded: image_22.jpg

 48%|████▊     | 23/48 [00:17<00:19,  1.29it/s]

Downloaded: image_23.jpg

 50%|█████     | 24/48 [00:18<00:19,  1.24it/s]

Downloaded: image_24.jpg

 52%|█████▏    | 25/48 [00:19<00:18,  1.25it/s]

Downloaded: image_25.jpg

 54%|█████▍    | 26/48 [00:19<00:17,  1.28it/s]

Downloaded: image_26.jpg

 56%|█████▋    | 27/48 [00:20<00:15,  1.34it/s]

Downloaded: image_27.jpg

 58%|█████▊    | 28/48 [00:20<00:13,  1.43it/s]

Downloaded: image_28.jpg

 60%|██████    | 29/48 [00:21<00:12,  1.51it/s]

Downloaded: image_29.jpg

 62%|██████▎   | 30/48 [00:22<00:11,  1.60it/s]

Downloaded: image_30.jpg

 65%|██████▍   | 31/48 [00:22<00:10,  1.62it/s]

Downloaded: image_31.jpg

 67%|██████▋   | 32/48 [00:23<00:12,  1.25it/s]

Failed to download image_32.jpg: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg : 403 Client Error: Forbidden for url: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg

 69%|██████▉   | 33/48 [00:24<00:10,  1.37it/s]

Downloaded: image_33.jpg

 71%|███████   | 34/48 [00:25<00:09,  1.47it/s]

Downloaded: image_34.jpg

 73%|███████▎  | 35/48 [00:25<00:08,  1.57it/s]

Downloaded: image_35.jpg

 75%|███████▌  | 36/48 [00:26<00:07,  1.63it/s]

Downloaded: image_36.jpg

 77%|███████▋  | 37/48 [00:26<00:06,  1.66it/s]

Downloaded: image_37.jpg

 79%|███████▉  | 38/48 [00:27<00:06,  1.67it/s]

Downloaded: image_38.jpg

 81%|████████▏ | 39/48 [00:27<00:05,  1.67it/s]

Downloaded: image_39.jpg

 83%|████████▎ | 40/48 [00:28<00:04,  1.70it/s]

Downloaded: image_40.jpg

 85%|████████▌ | 41/48 [00:29<00:04,  1.70it/s]

Downloaded: image_41.jpg

 88%|████████▊ | 42/48 [00:29<00:03,  1.57it/s]

Downloaded: image_42.jpg

 90%|████████▉ | 43/48 [00:30<00:03,  1.42it/s]

Downloaded: image_43.jpg

 92%|█████████▏| 44/48 [00:31<00:02,  1.46it/s]

Downloaded: image_44.jpg

 94%|█████████▍| 45/48 [00:31<00:01,  1.51it/s]

Downloaded: image_45.jpg

 96%|█████████▌| 46/48 [00:32<00:01,  1.50it/s]

Downloaded: image_46.jpg

 98%|█████████▊| 47/48 [00:33<00:00,  1.52it/s]

Downloaded: image_47.jpg

100%|██████████| 48/48 [00:33<00:00,  1.42it/s]

Downloaded: image_48.jpg

In [12]:
# STEP 8: Update the Excel file with the local image paths
df['Local Image Path'] = path
df.to_excel("stock_images_data.xlsx", index=False)

In [13]:
df

,Image URL,Tags,Likes,Comments,Local Image Path
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Sky Clouds, Blue Atmosphere,",196,55,downloaded_images\image_1.jpg
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Ornithology, Hummingbird Bird,",76,20,downloaded_images\image_2.jpg
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainbow, Rainfall, Sea,",282,106,downloaded_images\image_3.jpg
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Road, Sakura Japan, Cherry Blossoms,",42,11,downloaded_images\image_4.jpg
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Marguerite, Cape Plant Flower,",39,15,downloaded_images\image_5.jpg
5,https://cdn.pixabay.com/photo/2021/11/13/23/06...,Tree Relaxing Under Rest The,522,108,downloaded_images\image_6.jpg
6,https://cdn.pixabay.com/photo/2022/04/07/02/56...,"Rabbit, Cottontail Wild Grass",51,10,downloaded_images\image_7.jpg
7,https://cdn.pixabay.com/photo/2022/03/19/21/11...,"Crocus, Flowers, Plant Spring,",135,44,downloaded_images\image_8.jpg
8,https://cdn.pixabay.com/photo/2022/04/09/17/30...,"Drink, Coffee, Vacation, Café, Table",26,5,downloaded_images\image_9.jpg
9,https://cdn.pixabay.com/photo/2022/03/25/19/24...,"Fall, Epic, Nature, Light Waterfall,",96,21,downloaded_images\image_10.jpg
10,https://cdn.pixabay.com/photo/2021/08/25/20/42...,"Nature Field, Sunrise, Dawn, Morning,",807,131,downloaded_images\image_11.jpg
11,https://cdn.pixabay.com/photo/2022/04/04/18/03...,"Robin, Birdwatching, Bird, Animal",69,19,downloaded_images\image_12.jpg
12,https://cdn.pixabay.com/photo/2022/04/04/07/58...,"Spring Soil, Bloom Flowers, Seedlings,",42,9,downloaded_images\image_13.jpg
13,https://cdn.pixabay.com/photo/2022/03/23/21/27...,"Hills Road, Countryside, Highway,",53,14,downloaded_images\image_14.jpg
14,https://cdn.pixabay.com/photo/2022/03/27/15/03...,"Monochrome, Cityscape, City Bridge,",45,13,downloaded_images\image_15.jpg
15,https://cdn.pixabay.com/photo/2022/03/25/17/54...,"Water Spring, Sakura, Cherry Blossoms,",70,12,downloaded_images\image_16.jpg
16,https://cdn.pixabay.com/photo/2022/04/01/19/03...,"Eggs, Template, Background, Art Easter,",5,2,downloaded_images\image_17.jpg
17,https://cdn.pixabay.com/photo/2022/01/31/12/46...,"Indian Species Ornithology, Chat, Bird,",171,53,downloaded_images\image_18.jpg
18,https://cdn.pixabay.com/photo/2022/01/18/16/49...,"Night, Village, Winter, Season Town,",109,15,downloaded_images\image_19.jpg
19,https://cdn.pixabay.com/photo/2022/04/09/17/42...,"Bloom Flower, Pansy, Viola, Blossom,",55,36,downloaded_images\image_20.jpg
20,https://cdn.pixabay.com/photo/2021/08/30/21/29...,"Architecture, Lake, Port, Vacations",276,49,downloaded_images\image_21.jpg
21,https://cdn.pixabay.com/photo/2022/03/16/02/03...,"Flowers, Sunflowers, Plant",54,21,downloaded_images\image_22.jpg
22,https://cdn.pixabay.com/photo/2022/03/28/18/41...,"Spring, Coffee, Flowers, Morning",40,10,downloaded_images\image_23.jpg
23,https://cdn.pixabay.com/photo/2022/02/12/06/21...,"Lake, Peak, Roys Mountains Wanaka,",69,19,downloaded_images\image_24.jpg
24,https://cdn.pixabay.com/photo/2021/11/21/21/14...,"Thank many downloads and you, likes. for every...",197,0,downloaded_images\image_25.jpg
25,https://cdn.pixabay.com/photo/2021/08/22/15/48...,"Exploration Beach, Outdoors, Nature,",272,150,downloaded_images\image_26.jpg
26,https://cdn.pixabay.com/photo/2022/03/03/11/18...,West Danish Jutland. during Shot Coast of suns...,48,11,downloaded_images\image_27.jpg
27,https://cdn.pixabay.com/photo/2022/03/16/21/01...,"Bird, Penguin, Animal Gentoo",93,22,downloaded_images\image_28.jpg
28,https://cdn.pixabay.com/photo/2021/11/26/20/45...,"Sea, Water, Tree Lantern, Heaven, Beach,",243,31,downloaded_images\image_29.jpg
29,https://cdn.pixabay.com/photo/2022/04/03/05/03...,"Spring, Easter, Easter Bunny",17,10,downloaded_images\image_30.jpg
30,https://cdn.pixabay.com/photo/2018/01/14/23/12...,on green rock during brown lake daytime trees ...,3098,495,downloaded_images\image_31.jpg
31,https://cdn.pixabay.com/photo/2022/02/27/19/46...,"Tower, Eiffel Tourist Attraction, Travel",83,21,downloaded_images\image_32.jpg
32,https://cdn.pixabay.com/photo/2022/04/07/22/23...,"Standing Stones, Menhir, Clouds, Stones",64,49,downloaded_images\image_33.jpg
33,https://cdn.pixabay.com/photo/2022/01/13/18/05...,"Path Road, Winter, Snow, Trees, Frost,",133,24,downloaded_images\image_34.jpg
34,https://cdn.pixabay.com/photo/2022/04/10/07/03...,"Bird, Woodpecker",28,20,downloaded_images\image_35.jpg
35,https://cdn.pixabay.com/photo/2021/11/25/19/50...,"Tape, Cassette, Classic Retro, Music,",134,20,downloaded_images\image_36.jpg
36,https://cdn.pixabay.com/photo/2022/01/10/15/29...,"Power Energy, Clouds, Wind Mills,",144,101,downloaded_images\image_37.jpg
37,https://cdn.pixabay.com/photo/2022/02/15/07/27...,"Tartini, Travel, Square, Tourism, Piran",70,19,downloaded_images\image_38.jpg
38,https://cdn.pixabay.com/photo/2022/04/11/04/33...,"Eggs, Nest, Colored Eggs Easter",29,0,downloaded_images\image_39.jpg
39,https://cdn.pixabay.com/photo/2022/02/07/22/27...,"Nature, Winter, Season, Travel Outdoors,",111,24,downloaded_images\image_40.jpg
40,https://cdn.pixabay.com/photo/2022/04/11/09/40...,"Glacier, Dying Glacier Glaciers, Melting",36,27,downloaded_images\image_41.jpg
41,https://cdn.pixabay.com/photo/2021/11/01/21/31...,"Jungle, Nature Tropical, Green, Forest,",135,22,downloaded_images\image_42.jpg
42,https://cdn.pixabay.com/photo/2022/02/05/08/13...,"Flower, Tulip, Petals Bloom, Blossom,",92,35,downloaded_images\image_43.jpg
43,https://cdn.pixabay.com/photo/2022/04/07/13/06...,"Flowers, Petals Pink",62,0,downloaded_images\image_44.jpg
44,https://cdn.pixabay.com/photo/2022/02/22/03/22...,"Passiflora, Flower, Passion Flower",97,66,downloaded_images\image_45.jpg
45,https://cdn.pixabay.com/photo/2021/11/02/21/57...,"Blessing Faith, Prayer, Hope, Religion,",175,57,downloaded_images\image_46.jpg
46,https://cdn.pixabay.com/photo/2022/04/09/10/13...,"Star, Cosmos Space, Universe, Galaxy,",45,40,downloaded_images\image_47.jpg
47,https://cdn.pixabay.com/photo/2022/03/31/09/25...,"Macro Insect, Dragonfly, Nature,",19,3,downloaded_images\image_48.jpg

In [18]:
# STEP 9: Clone the dataset
df_new = df.copy()
# two columns path and tags are there reset of the columns are removed
df_new = df_new[['Local Image Path', 'Tags']]
df_new.to_excel("stock_images_data_cloned.xlsx", index=False)
df_new

,Local Image Path,Tags
0,downloaded_images\image_1.jpg,"Sky, Sky Clouds, Blue Atmosphere,"
1,downloaded_images\image_2.jpg,"Ornithology, Hummingbird Bird,"
2,downloaded_images\image_3.jpg,"Subtropical Rainbow, Rainfall, Sea,"
3,downloaded_images\image_4.jpg,"Road, Sakura Japan, Cherry Blossoms,"
4,downloaded_images\image_5.jpg,"Marguerite, Cape Plant Flower,"
5,downloaded_images\image_6.jpg,Tree Relaxing Under Rest The
6,downloaded_images\image_7.jpg,"Rabbit, Cottontail Wild Grass"
7,downloaded_images\image_8.jpg,"Crocus, Flowers, Plant Spring,"
8,downloaded_images\image_9.jpg,"Drink, Coffee, Vacation, Café, Table"
9,downloaded_images\image_10.jpg,"Fall, Epic, Nature, Light Waterfall,"
10,downloaded_images\image_11.jpg,"Nature Field, Sunrise, Dawn, Morning,"
11,downloaded_images\image_12.jpg,"Robin, Birdwatching, Bird, Animal"
12,downloaded_images\image_13.jpg,"Spring Soil, Bloom Flowers, Seedlings,"
13,downloaded_images\image_14.jpg,"Hills Road, Countryside, Highway,"
14,downloaded_images\image_15.jpg,"Monochrome, Cityscape, City Bridge,"
15,downloaded_images\image_16.jpg,"Water Spring, Sakura, Cherry Blossoms,"
16,downloaded_images\image_17.jpg,"Eggs, Template, Background, Art Easter,"
17,downloaded_images\image_18.jpg,"Indian Species Ornithology, Chat, Bird,"
18,downloaded_images\image_19.jpg,"Night, Village, Winter, Season Town,"
19,downloaded_images\image_20.jpg,"Bloom Flower, Pansy, Viola, Blossom,"
20,downloaded_images\image_21.jpg,"Architecture, Lake, Port, Vacations"
21,downloaded_images\image_22.jpg,"Flowers, Sunflowers, Plant"
22,downloaded_images\image_23.jpg,"Spring, Coffee, Flowers, Morning"
23,downloaded_images\image_24.jpg,"Lake, Peak, Roys Mountains Wanaka,"
24,downloaded_images\image_25.jpg,"Thank many downloads and you, likes. for every..."
25,downloaded_images\image_26.jpg,"Exploration Beach, Outdoors, Nature,"
26,downloaded_images\image_27.jpg,West Danish Jutland. during Shot Coast of suns...
27,downloaded_images\image_28.jpg,"Bird, Penguin, Animal Gentoo"
28,downloaded_images\image_29.jpg,"Sea, Water, Tree Lantern, Heaven, Beach,"
29,downloaded_images\image_30.jpg,"Spring, Easter, Easter Bunny"
30,downloaded_images\image_31.jpg,on green rock during brown lake daytime trees ...
31,downloaded_images\image_32.jpg,"Tower, Eiffel Tourist Attraction, Travel"
32,downloaded_images\image_33.jpg,"Standing Stones, Menhir, Clouds, Stones"
33,downloaded_images\image_34.jpg,"Path Road, Winter, Snow, Trees, Frost,"
34,downloaded_images\image_35.jpg,"Bird, Woodpecker"
35,downloaded_images\image_36.jpg,"Tape, Cassette, Classic Retro, Music,"
36,downloaded_images\image_37.jpg,"Power Energy, Clouds, Wind Mills,"
37,downloaded_images\image_38.jpg,"Tartini, Travel, Square, Tourism, Piran"
38,downloaded_images\image_39.jpg,"Eggs, Nest, Colored Eggs Easter"
39,downloaded_images\image_40.jpg,"Nature, Winter, Season, Travel Outdoors,"
40,downloaded_images\image_41.jpg,"Glacier, Dying Glacier Glaciers, Melting"
41,downloaded_images\image_42.jpg,"Jungle, Nature Tropical, Green, Forest,"
42,downloaded_images\image_43.jpg,"Flower, Tulip, Petals Bloom, Blossom,"
43,downloaded_images\image_44.jpg,"Flowers, Petals Pink"
44,downloaded_images\image_45.jpg,"Passiflora, Flower, Passion Flower"
45,downloaded_images\image_46.jpg,"Blessing Faith, Prayer, Hope, Religion,"
46,downloaded_images\image_47.jpg,"Star, Cosmos Space, Universe, Galaxy,"
47,downloaded_images\image_48.jpg,"Macro Insect, Dragonfly, Nature,"

In [20]:
# STEP 10: Make different folder for unique tags and move the images to the respective folders
for index, row in df_new.iterrows():
    image_path = row['Local Image Path']
    if not os.path.exists(image_path):
        print(f"Missing file, skipping: {image_path}")
        continue

    tags = [tag.strip().strip(',.') for tag in re.split(r',\s*', row['Tags']) if tag.strip()]
    for tag in tags:
        tag_folder = os.path.join("tagged_images", tag)
        os.makedirs(tag_folder, exist_ok=True)
        shutil.copy2(image_path, tag_folder)

Missing file, skipping: downloaded_images\image_32.jpg

In [23]:
# STEP 11: Create a zip file of the tagged images folder
shutil.make_archive("tagged_images", 'zip', "tagged_images")
# length of the folder and files in tagedd images folder
total_images = 0
for root, dirs, files in os.walk("tagged_images"):
    total_images += len(files) 

print(f"Total images in tagged_images folder: {total_images}")

Total images in tagged_images folder: 297

STOCK IMAGE SCRAPPER AND CREATING THE IMAGE DATASET CREATION IS DONE BY VINAYAK MISHRA