# Stock Image Scraper 📸

scrappe the image and store the data in the excel

In [1]:
# STEP 1:- Importing the required libraries
import time
import requests
import pandas as pd
from tqdm import tqdm
import chromedriver_binary
from bs4 import BeautifulSoup
from selenium import webdriver
from openpyxl import Workbook
import re
import os
import urllib.request
from urllib.parse import urljoin
import shutil

In [2]:
# STEP :-2:- Setting up the Selenium WebDriver
driver = webdriver.Chrome()
driver.get("https://stock-pictures.netlify.app/")
time.sleep(5)  # Wait for the page to load

The chromedriver version (147.0.7727.57) detected in PATH at c:\Users\Nbinary\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\chromedriver_binary\chromedriver.exe might not be compatible with the detected chrome version (148.0.7778.181); currently, chromedriver 148.0.7778.178 is recommended for chrome 148.*, so it is advised to delete the driver in PATH and retry

In [3]:
# STEP 3:- Scrapping the url
soup = BeautifulSoup(driver.page_source, "html.parser")
image_elements = soup.select('img.source-img[src$=".jpg"]')
print(f"Found {len(image_elements)} images on the page.")

Found 48 images on the page.

We have to extract the image url,name tags,like and comment on each image

In [4]:
# STEP 3:- Scraping the image details
# image url, name tags, likes and comments on each image
image_data = []
for sp in soup.find_all('div', class_='container'):
    img = sp.find('img')
    
    # 1. Safely check if img exists AND has a src attribute before proceeding
    if img and img.get('src') and 'gif' not in img.get('src'):
        link = img.get('src')
        
        # 2. Safely extract tags (Default to empty string if missing)
        tags_div = sp.find('div', class_='tags')
        tags_text = ""
        if tags_div:
            # Assuming the first 7 chars were something like "Tags: "
            # A safer way is replacing the specific word, or just matching words
            raw_tags = tags_div.text[7:].strip().split(' ')
            tags_text = ' '.join(list(set(raw_tags)))
        
        # 3. Safely extract likes and comments (Default to 0 if missing)
        likes, comments = 0, 0
        likes_comments_div = sp.find('div', class_='likes-comments')
        
        if likes_comments_div:
            spans = likes_comments_div.find_all('span')
            
            # re.search(r'\d+', text) finds the first sequence of numbers in a string
            if len(spans) > 0:
                likes_match = re.search(r'\d+', spans[0].text)
                likes = int(likes_match.group()) if likes_match else 0
                
            if len(spans) > 1:
                comments_match = re.search(r'\d+', spans[1].text)
                comments = int(comments_match.group()) if comments_match else 0
        
        image_data.append([link, tags_text, likes, comments])

In [5]:
# STEP 4: Make in to a dataframe
df = pd.DataFrame(image_data, columns=['Image URL', 'Tags', 'Likes', 'Comments'])

In [6]:
df

,Image URL,Tags,Likes,Comments
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Clouds, Blue Sky, Atmosphere, Sky",196,55
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Ornithology, Hummingbird Bird,",76,20
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainfall, Rainbow, Sea,",282,106
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Blossoms, Cherry Road, Sakura Japan,",42,11
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Plant Flower, Marguerite, Cape",39,15
5,https://cdn.pixabay.com/photo/2021/11/13/23/06...,Relaxing The Under Rest Tree,522,108
6,https://cdn.pixabay.com/photo/2022/04/07/02/56...,"Cottontail Wild Rabbit, Grass",51,10
7,https://cdn.pixabay.com/photo/2022/03/19/21/11...,"Plant Spring, Crocus, Flowers,",135,44
8,https://cdn.pixabay.com/photo/2022/04/09/17/30...,"Coffee, Drink, Café, Vacation, Table",26,5
9,https://cdn.pixabay.com/photo/2022/03/25/19/24...,"Waterfall, Fall, Light Nature, Epic,",96,21
10,https://cdn.pixabay.com/photo/2021/08/25/20/42...,"Dawn, Field, Morning, Sunrise, Nature",807,131
11,https://cdn.pixabay.com/photo/2022/04/04/18/03...,"Animal Robin, Birdwatching, Bird,",69,19
12,https://cdn.pixabay.com/photo/2022/04/04/07/58...,"Spring Bloom Soil, Flowers, Seedlings,",42,9
13,https://cdn.pixabay.com/photo/2022/03/23/21/27...,"Road, Hills Countryside, Highway,",53,14
14,https://cdn.pixabay.com/photo/2022/03/27/15/03...,"Cityscape, City Bridge, Monochrome,",45,13
15,https://cdn.pixabay.com/photo/2022/03/25/17/54...,"Sakura, Cherry Blossoms, Water Spring,",70,12
16,https://cdn.pixabay.com/photo/2022/04/01/19/03...,"Background, Art Template, Easter, Eggs,",5,2
17,https://cdn.pixabay.com/photo/2022/01/31/12/46...,"Species Chat, Ornithology, Bird, Indian",171,53
18,https://cdn.pixabay.com/photo/2022/01/18/16/49...,"Season Night, Village, Town, Winter,",109,15
19,https://cdn.pixabay.com/photo/2022/04/09/17/42...,"Blossom, Flower, Bloom Viola, Pansy,",55,36
20,https://cdn.pixabay.com/photo/2021/08/30/21/29...,"Port, Architecture, Vacations Lake,",276,49
21,https://cdn.pixabay.com/photo/2022/03/16/02/03...,"Sunflowers, Flowers, Plant",54,21
22,https://cdn.pixabay.com/photo/2022/03/28/18/41...,"Coffee, Morning Flowers, Spring,",40,10
23,https://cdn.pixabay.com/photo/2022/02/12/06/21...,"Mountains Wanaka, Roys Lake, Peak,",69,19
24,https://cdn.pixabay.com/photo/2021/11/21/21/14...,"Thank and everyone. many downloads you, likes....",197,0
25,https://cdn.pixabay.com/photo/2021/08/22/15/48...,"Beach, Outdoors, Exploration Nature,",272,150
26,https://cdn.pixabay.com/photo/2022/03/03/11/18...,Jutland. during Shot sunset. The of West Danis...,48,11
27,https://cdn.pixabay.com/photo/2022/03/16/21/01...,"Animal Gentoo Penguin, Bird,",93,22
28,https://cdn.pixabay.com/photo/2021/11/26/20/45...,"Water, Lantern, Heaven, Sea, Beach, Tree",243,31
29,https://cdn.pixabay.com/photo/2022/04/03/05/03...,"Easter, Easter Spring, Bunny",17,10
30,https://cdn.pixabay.com/photo/2018/01/14/23/12...,during brown trees green formation on lake roc...,3098,495
31,https://cdn.pixabay.com/photo/2022/02/27/19/46...,"Attraction, Tower, Tourist Eiffel Travel",83,21
32,https://cdn.pixabay.com/photo/2022/04/07/22/23...,"Clouds, Standing Stones Stones, Menhir,",64,49
33,https://cdn.pixabay.com/photo/2022/01/13/18/05...,"Road, Snow, Trees, Path Winter, Frost,",133,24
34,https://cdn.pixabay.com/photo/2022/04/10/07/03...,"Woodpecker Bird,",28,20
35,https://cdn.pixabay.com/photo/2021/11/25/19/50...,"Retro, Classic Tape, Cassette, Music,",134,20
36,https://cdn.pixabay.com/photo/2022/01/10/15/29...,"Clouds, Power Mills, Wind Energy,",144,101
37,https://cdn.pixabay.com/photo/2022/02/15/07/27...,"Tourism, Square, Tartini, Piran Travel,",70,19
38,https://cdn.pixabay.com/photo/2022/04/11/04/33...,"Nest, Eggs Colored Easter Eggs,",29,0
39,https://cdn.pixabay.com/photo/2022/02/07/22/27...,"Outdoors, Season, Nature, Winter, Travel",111,24
40,https://cdn.pixabay.com/photo/2022/04/11/09/40...,"Glaciers, Glacier Glacier, Dying Melting",36,27
41,https://cdn.pixabay.com/photo/2021/11/01/21/31...,"Forest, Green, Jungle, Tropical, Nature",135,22
42,https://cdn.pixabay.com/photo/2022/02/05/08/13...,"Blossom, Petals Flower, Bloom, Tulip,",92,35
43,https://cdn.pixabay.com/photo/2022/04/07/13/06...,"Pink Flowers, Petals",62,0
44,https://cdn.pixabay.com/photo/2022/02/22/03/22...,"Flower Flower, Passion Passiflora,",97,66
45,https://cdn.pixabay.com/photo/2021/11/02/21/57...,"Religion, Hope, Faith, Prayer, Blessing",175,57
46,https://cdn.pixabay.com/photo/2022/04/09/10/13...,"Star, Universe, Galaxy, Cosmos Space,",45,40
47,https://cdn.pixabay.com/photo/2022/03/31/09/25...,"Dragonfly, Insect, Macro Nature,",19,3

In [7]:
# STEP 5: Close the Selenium WebDriver
driver.quit()

In [8]:
# STEP 6: Save the data to an Excel file
df.to_excel("stock_images_data.xlsx", index=False)

In [9]:
# STEP 7: Download the images to a local folder
# Create a folder to save the images
path=[]
os.makedirs("downloaded_images", exist_ok=True)
# Use a browser-like User-Agent to avoid being blocked by the server
download_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}
# Download each image
for index, row in tqdm(df.iterrows(), total=len(df)):
    image_url = row['Image URL']
    if image_url.startswith('/'):
        image_url = urljoin("https://stock-pictures.netlify.app/", image_url)
    image_name = f"image_{index + 1}.jpg"
    save_path = os.path.join("downloaded_images", image_name)
    path.append(save_path)
    try:
        response = requests.get(image_url, headers=download_headers, timeout=30, stream=True)
        response.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=10240):
                if chunk:
                    f.write(chunk)
        print(f"Downloaded: {image_name}")
    except Exception as e:
        print(f"Failed to download {image_name}: {image_url} : {e}")

  2%|▏         | 1/48 [00:00<00:36,  1.29it/s]

Downloaded: image_1.jpg

  4%|▍         | 2/48 [00:01<00:37,  1.23it/s]

Downloaded: image_2.jpg

  6%|▋         | 3/48 [00:02<00:35,  1.26it/s]

Downloaded: image_3.jpg

  8%|▊         | 4/48 [00:03<00:33,  1.31it/s]

Downloaded: image_4.jpg

 10%|█         | 5/48 [00:03<00:30,  1.43it/s]

Downloaded: image_5.jpg

 12%|█▎        | 6/48 [00:04<00:27,  1.51it/s]

Downloaded: image_6.jpg

 15%|█▍        | 7/48 [00:04<00:26,  1.56it/s]

Downloaded: image_7.jpg

 17%|█▋        | 8/48 [00:05<00:24,  1.61it/s]

Downloaded: image_8.jpg

 19%|█▉        | 9/48 [00:06<00:24,  1.60it/s]

Downloaded: image_9.jpg

 21%|██        | 10/48 [00:06<00:23,  1.62it/s]

Downloaded: image_10.jpg

 23%|██▎       | 11/48 [00:07<00:22,  1.64it/s]

Downloaded: image_11.jpg

 25%|██▌       | 12/48 [00:07<00:21,  1.68it/s]

Downloaded: image_12.jpg

 27%|██▋       | 13/48 [00:08<00:20,  1.68it/s]

Downloaded: image_13.jpg

 29%|██▉       | 14/48 [00:08<00:19,  1.73it/s]

Downloaded: image_14.jpg

 31%|███▏      | 15/48 [00:09<00:18,  1.75it/s]

Downloaded: image_15.jpg

 33%|███▎      | 16/48 [00:10<00:18,  1.76it/s]

Downloaded: image_16.jpg

 35%|███▌      | 17/48 [00:11<00:23,  1.32it/s]

Downloaded: image_17.jpg

 38%|███▊      | 18/48 [00:11<00:20,  1.44it/s]

Downloaded: image_18.jpg

 40%|███▉      | 19/48 [00:12<00:19,  1.52it/s]

Downloaded: image_19.jpg

 42%|████▏     | 20/48 [00:12<00:17,  1.59it/s]

Downloaded: image_20.jpg

 44%|████▍     | 21/48 [00:13<00:16,  1.62it/s]

Downloaded: image_21.jpg

 46%|████▌     | 22/48 [00:14<00:15,  1.63it/s]

Downloaded: image_22.jpg

 48%|████▊     | 23/48 [00:14<00:15,  1.58it/s]

Downloaded: image_23.jpg

 50%|█████     | 24/48 [00:15<00:16,  1.49it/s]

Downloaded: image_24.jpg

 52%|█████▏    | 25/48 [00:16<00:15,  1.49it/s]

Downloaded: image_25.jpg

 54%|█████▍    | 26/48 [00:16<00:14,  1.52it/s]

Downloaded: image_26.jpg

 56%|█████▋    | 27/48 [00:17<00:13,  1.58it/s]

Downloaded: image_27.jpg

 58%|█████▊    | 28/48 [00:18<00:12,  1.65it/s]

Downloaded: image_28.jpg

 60%|██████    | 29/48 [00:18<00:11,  1.69it/s]

Downloaded: image_29.jpg

 62%|██████▎   | 30/48 [00:19<00:10,  1.69it/s]

Downloaded: image_30.jpg

 65%|██████▍   | 31/48 [00:19<00:09,  1.71it/s]

Downloaded: image_31.jpg

 67%|██████▋   | 32/48 [00:21<00:12,  1.26it/s]

Failed to download image_32.jpg: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg : 403 Client Error: Forbidden for url: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg

 69%|██████▉   | 33/48 [00:21<00:10,  1.39it/s]

Downloaded: image_33.jpg

 71%|███████   | 34/48 [00:22<00:09,  1.48it/s]

Downloaded: image_34.jpg

 73%|███████▎  | 35/48 [00:22<00:08,  1.57it/s]

Downloaded: image_35.jpg

 75%|███████▌  | 36/48 [00:23<00:07,  1.64it/s]

Downloaded: image_36.jpg

 77%|███████▋  | 37/48 [00:23<00:06,  1.67it/s]

Downloaded: image_37.jpg

 79%|███████▉  | 38/48 [00:24<00:05,  1.72it/s]

Downloaded: image_38.jpg

 81%|████████▏ | 39/48 [00:24<00:05,  1.74it/s]

Downloaded: image_39.jpg

 83%|████████▎ | 40/48 [00:25<00:04,  1.76it/s]

Downloaded: image_40.jpg

 85%|████████▌ | 41/48 [00:26<00:03,  1.77it/s]

Downloaded: image_41.jpg

 88%|████████▊ | 42/48 [00:26<00:03,  1.78it/s]

Downloaded: image_42.jpg

 90%|████████▉ | 43/48 [00:27<00:02,  1.74it/s]

Downloaded: image_43.jpg

 92%|█████████▏| 44/48 [00:27<00:02,  1.75it/s]

Downloaded: image_44.jpg

 94%|█████████▍| 45/48 [00:28<00:01,  1.78it/s]

Downloaded: image_45.jpg

 96%|█████████▌| 46/48 [00:28<00:01,  1.71it/s]

Downloaded: image_46.jpg

 98%|█████████▊| 47/48 [00:29<00:00,  1.60it/s]

Downloaded: image_47.jpg

100%|██████████| 48/48 [00:30<00:00,  1.58it/s]

Downloaded: image_48.jpg

In [10]:
# STEP 8: Update the Excel file with the local image paths
df['Local Image Path'] = path
df.to_excel("stock_images_data.xlsx", index=False)

In [11]:
df

,Image URL,Tags,Likes,Comments,Local Image Path
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Clouds, Blue Sky, Atmosphere, Sky",196,55,downloaded_images\image_1.jpg
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Ornithology, Hummingbird Bird,",76,20,downloaded_images\image_2.jpg
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainfall, Rainbow, Sea,",282,106,downloaded_images\image_3.jpg
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Blossoms, Cherry Road, Sakura Japan,",42,11,downloaded_images\image_4.jpg
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Plant Flower, Marguerite, Cape",39,15,downloaded_images\image_5.jpg
5,https://cdn.pixabay.com/photo/2021/11/13/23/06...,Relaxing The Under Rest Tree,522,108,downloaded_images\image_6.jpg
6,https://cdn.pixabay.com/photo/2022/04/07/02/56...,"Cottontail Wild Rabbit, Grass",51,10,downloaded_images\image_7.jpg
7,https://cdn.pixabay.com/photo/2022/03/19/21/11...,"Plant Spring, Crocus, Flowers,",135,44,downloaded_images\image_8.jpg
8,https://cdn.pixabay.com/photo/2022/04/09/17/30...,"Coffee, Drink, Café, Vacation, Table",26,5,downloaded_images\image_9.jpg
9,https://cdn.pixabay.com/photo/2022/03/25/19/24...,"Waterfall, Fall, Light Nature, Epic,",96,21,downloaded_images\image_10.jpg
10,https://cdn.pixabay.com/photo/2021/08/25/20/42...,"Dawn, Field, Morning, Sunrise, Nature",807,131,downloaded_images\image_11.jpg
11,https://cdn.pixabay.com/photo/2022/04/04/18/03...,"Animal Robin, Birdwatching, Bird,",69,19,downloaded_images\image_12.jpg
12,https://cdn.pixabay.com/photo/2022/04/04/07/58...,"Spring Bloom Soil, Flowers, Seedlings,",42,9,downloaded_images\image_13.jpg
13,https://cdn.pixabay.com/photo/2022/03/23/21/27...,"Road, Hills Countryside, Highway,",53,14,downloaded_images\image_14.jpg
14,https://cdn.pixabay.com/photo/2022/03/27/15/03...,"Cityscape, City Bridge, Monochrome,",45,13,downloaded_images\image_15.jpg
15,https://cdn.pixabay.com/photo/2022/03/25/17/54...,"Sakura, Cherry Blossoms, Water Spring,",70,12,downloaded_images\image_16.jpg
16,https://cdn.pixabay.com/photo/2022/04/01/19/03...,"Background, Art Template, Easter, Eggs,",5,2,downloaded_images\image_17.jpg
17,https://cdn.pixabay.com/photo/2022/01/31/12/46...,"Species Chat, Ornithology, Bird, Indian",171,53,downloaded_images\image_18.jpg
18,https://cdn.pixabay.com/photo/2022/01/18/16/49...,"Season Night, Village, Town, Winter,",109,15,downloaded_images\image_19.jpg
19,https://cdn.pixabay.com/photo/2022/04/09/17/42...,"Blossom, Flower, Bloom Viola, Pansy,",55,36,downloaded_images\image_20.jpg
20,https://cdn.pixabay.com/photo/2021/08/30/21/29...,"Port, Architecture, Vacations Lake,",276,49,downloaded_images\image_21.jpg
21,https://cdn.pixabay.com/photo/2022/03/16/02/03...,"Sunflowers, Flowers, Plant",54,21,downloaded_images\image_22.jpg
22,https://cdn.pixabay.com/photo/2022/03/28/18/41...,"Coffee, Morning Flowers, Spring,",40,10,downloaded_images\image_23.jpg
23,https://cdn.pixabay.com/photo/2022/02/12/06/21...,"Mountains Wanaka, Roys Lake, Peak,",69,19,downloaded_images\image_24.jpg
24,https://cdn.pixabay.com/photo/2021/11/21/21/14...,"Thank and everyone. many downloads you, likes....",197,0,downloaded_images\image_25.jpg
25,https://cdn.pixabay.com/photo/2021/08/22/15/48...,"Beach, Outdoors, Exploration Nature,",272,150,downloaded_images\image_26.jpg
26,https://cdn.pixabay.com/photo/2022/03/03/11/18...,Jutland. during Shot sunset. The of West Danis...,48,11,downloaded_images\image_27.jpg
27,https://cdn.pixabay.com/photo/2022/03/16/21/01...,"Animal Gentoo Penguin, Bird,",93,22,downloaded_images\image_28.jpg
28,https://cdn.pixabay.com/photo/2021/11/26/20/45...,"Water, Lantern, Heaven, Sea, Beach, Tree",243,31,downloaded_images\image_29.jpg
29,https://cdn.pixabay.com/photo/2022/04/03/05/03...,"Easter, Easter Spring, Bunny",17,10,downloaded_images\image_30.jpg
30,https://cdn.pixabay.com/photo/2018/01/14/23/12...,during brown trees green formation on lake roc...,3098,495,downloaded_images\image_31.jpg
31,https://cdn.pixabay.com/photo/2022/02/27/19/46...,"Attraction, Tower, Tourist Eiffel Travel",83,21,downloaded_images\image_32.jpg
32,https://cdn.pixabay.com/photo/2022/04/07/22/23...,"Clouds, Standing Stones Stones, Menhir,",64,49,downloaded_images\image_33.jpg
33,https://cdn.pixabay.com/photo/2022/01/13/18/05...,"Road, Snow, Trees, Path Winter, Frost,",133,24,downloaded_images\image_34.jpg
34,https://cdn.pixabay.com/photo/2022/04/10/07/03...,"Woodpecker Bird,",28,20,downloaded_images\image_35.jpg
35,https://cdn.pixabay.com/photo/2021/11/25/19/50...,"Retro, Classic Tape, Cassette, Music,",134,20,downloaded_images\image_36.jpg
36,https://cdn.pixabay.com/photo/2022/01/10/15/29...,"Clouds, Power Mills, Wind Energy,",144,101,downloaded_images\image_37.jpg
37,https://cdn.pixabay.com/photo/2022/02/15/07/27...,"Tourism, Square, Tartini, Piran Travel,",70,19,downloaded_images\image_38.jpg
38,https://cdn.pixabay.com/photo/2022/04/11/04/33...,"Nest, Eggs Colored Easter Eggs,",29,0,downloaded_images\image_39.jpg
39,https://cdn.pixabay.com/photo/2022/02/07/22/27...,"Outdoors, Season, Nature, Winter, Travel",111,24,downloaded_images\image_40.jpg
40,https://cdn.pixabay.com/photo/2022/04/11/09/40...,"Glaciers, Glacier Glacier, Dying Melting",36,27,downloaded_images\image_41.jpg
41,https://cdn.pixabay.com/photo/2021/11/01/21/31...,"Forest, Green, Jungle, Tropical, Nature",135,22,downloaded_images\image_42.jpg
42,https://cdn.pixabay.com/photo/2022/02/05/08/13...,"Blossom, Petals Flower, Bloom, Tulip,",92,35,downloaded_images\image_43.jpg
43,https://cdn.pixabay.com/photo/2022/04/07/13/06...,"Pink Flowers, Petals",62,0,downloaded_images\image_44.jpg
44,https://cdn.pixabay.com/photo/2022/02/22/03/22...,"Flower Flower, Passion Passiflora,",97,66,downloaded_images\image_45.jpg
45,https://cdn.pixabay.com/photo/2021/11/02/21/57...,"Religion, Hope, Faith, Prayer, Blessing",175,57,downloaded_images\image_46.jpg
46,https://cdn.pixabay.com/photo/2022/04/09/10/13...,"Star, Universe, Galaxy, Cosmos Space,",45,40,downloaded_images\image_47.jpg
47,https://cdn.pixabay.com/photo/2022/03/31/09/25...,"Dragonfly, Insect, Macro Nature,",19,3,downloaded_images\image_48.jpg

In [12]:
# STEP 9: Clone the dataset
df_new = df.copy()
# two columns path and tags are there reset of the columns are removed
df_new = df_new[['Local Image Path', 'Tags']]
df_new.to_excel("stock_images_data_cloned.xlsx", index=False)
df_new

,Local Image Path,Tags
0,downloaded_images\image_1.jpg,"Clouds, Blue Sky, Atmosphere, Sky"
1,downloaded_images\image_2.jpg,"Ornithology, Hummingbird Bird,"
2,downloaded_images\image_3.jpg,"Subtropical Rainfall, Rainbow, Sea,"
3,downloaded_images\image_4.jpg,"Blossoms, Cherry Road, Sakura Japan,"
4,downloaded_images\image_5.jpg,"Plant Flower, Marguerite, Cape"
5,downloaded_images\image_6.jpg,Relaxing The Under Rest Tree
6,downloaded_images\image_7.jpg,"Cottontail Wild Rabbit, Grass"
7,downloaded_images\image_8.jpg,"Plant Spring, Crocus, Flowers,"
8,downloaded_images\image_9.jpg,"Coffee, Drink, Café, Vacation, Table"
9,downloaded_images\image_10.jpg,"Waterfall, Fall, Light Nature, Epic,"
10,downloaded_images\image_11.jpg,"Dawn, Field, Morning, Sunrise, Nature"
11,downloaded_images\image_12.jpg,"Animal Robin, Birdwatching, Bird,"
12,downloaded_images\image_13.jpg,"Spring Bloom Soil, Flowers, Seedlings,"
13,downloaded_images\image_14.jpg,"Road, Hills Countryside, Highway,"
14,downloaded_images\image_15.jpg,"Cityscape, City Bridge, Monochrome,"
15,downloaded_images\image_16.jpg,"Sakura, Cherry Blossoms, Water Spring,"
16,downloaded_images\image_17.jpg,"Background, Art Template, Easter, Eggs,"
17,downloaded_images\image_18.jpg,"Species Chat, Ornithology, Bird, Indian"
18,downloaded_images\image_19.jpg,"Season Night, Village, Town, Winter,"
19,downloaded_images\image_20.jpg,"Blossom, Flower, Bloom Viola, Pansy,"
20,downloaded_images\image_21.jpg,"Port, Architecture, Vacations Lake,"
21,downloaded_images\image_22.jpg,"Sunflowers, Flowers, Plant"
22,downloaded_images\image_23.jpg,"Coffee, Morning Flowers, Spring,"
23,downloaded_images\image_24.jpg,"Mountains Wanaka, Roys Lake, Peak,"
24,downloaded_images\image_25.jpg,"Thank and everyone. many downloads you, likes...."
25,downloaded_images\image_26.jpg,"Beach, Outdoors, Exploration Nature,"
26,downloaded_images\image_27.jpg,Jutland. during Shot sunset. The of West Danis...
27,downloaded_images\image_28.jpg,"Animal Gentoo Penguin, Bird,"
28,downloaded_images\image_29.jpg,"Water, Lantern, Heaven, Sea, Beach, Tree"
29,downloaded_images\image_30.jpg,"Easter, Easter Spring, Bunny"
30,downloaded_images\image_31.jpg,during brown trees green formation on lake roc...
31,downloaded_images\image_32.jpg,"Attraction, Tower, Tourist Eiffel Travel"
32,downloaded_images\image_33.jpg,"Clouds, Standing Stones Stones, Menhir,"
33,downloaded_images\image_34.jpg,"Road, Snow, Trees, Path Winter, Frost,"
34,downloaded_images\image_35.jpg,"Woodpecker Bird,"
35,downloaded_images\image_36.jpg,"Retro, Classic Tape, Cassette, Music,"
36,downloaded_images\image_37.jpg,"Clouds, Power Mills, Wind Energy,"
37,downloaded_images\image_38.jpg,"Tourism, Square, Tartini, Piran Travel,"
38,downloaded_images\image_39.jpg,"Nest, Eggs Colored Easter Eggs,"
39,downloaded_images\image_40.jpg,"Outdoors, Season, Nature, Winter, Travel"
40,downloaded_images\image_41.jpg,"Glaciers, Glacier Glacier, Dying Melting"
41,downloaded_images\image_42.jpg,"Forest, Green, Jungle, Tropical, Nature"
42,downloaded_images\image_43.jpg,"Blossom, Petals Flower, Bloom, Tulip,"
43,downloaded_images\image_44.jpg,"Pink Flowers, Petals"
44,downloaded_images\image_45.jpg,"Flower Flower, Passion Passiflora,"
45,downloaded_images\image_46.jpg,"Religion, Hope, Faith, Prayer, Blessing"
46,downloaded_images\image_47.jpg,"Star, Universe, Galaxy, Cosmos Space,"
47,downloaded_images\image_48.jpg,"Dragonfly, Insect, Macro Nature,"

In [17]:
# STEP 10: Make different folder for unique tags and move the images to the respective folders
paths=[]
for index, row in df_new.iterrows():
    image_path = row['Local Image Path']
    if not os.path.exists(image_path):
        print(f"Missing file, skipping: {image_path}")
        continue

    tags = [tag.strip().strip(',.') for tag in re.split(r',\s*', row['Tags']) if tag.strip()]
    for tag in tags:
        tag_folder = os.path.join("tagged_images", tag)
        paths.append(tag_folder)
        os.makedirs(tag_folder, exist_ok=True)
        shutil.copy2(image_path, tag_folder)

Missing file, skipping: downloaded_images\image_32.jpg

In [18]:
# STEP 11: Create a zip file of the tagged images folder
shutil.make_archive("tagged_images", 'zip', "tagged_images")
# length of the folder and files in tagedd images folder
total_images = 0
for root, dirs, files in os.walk("tagged_images"):
    total_images += len(files) 

print(f"Total images in tagged_images folder: {total_images}")

Total images in tagged_images folder: 363

STOCK IMAGE SCRAPPER AND CREATING THE IMAGE DATASET CREATION IS DONE BY VINAYAK MISHRA