# Stock Image Scraper 📸

scrappe the image and store the data in the excel

In [ ]:
# STEP 1:- Importing the required libraries
import time
import requests
import pandas as pd
from tqdm import tqdm
import chromedriver_binary
from bs4 import BeautifulSoup
from selenium import webdriver
from openpyxl import Workbook
import re
import os
import urllib.request
from urllib.parse import urljoin
import shutil

In [2]:
# STEP :-2:- Setting up the Selenium WebDriver
driver = webdriver.Chrome()
driver.get("https://stock-pictures.netlify.app/")
time.sleep(5)  # Wait for the page to load

The chromedriver version (147.0.7727.57) detected in PATH at c:\Users\Nbinary\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\chromedriver_binary\chromedriver.exe might not be compatible with the detected chrome version (148.0.7778.181); currently, chromedriver 148.0.7778.178 is recommended for chrome 148.*, so it is advised to delete the driver in PATH and retry

In [4]:
# STEP 3:- Scrapping the url
soup = BeautifulSoup(driver.page_source, "html.parser")
image_elements = soup.select('img.source-img[src$=".jpg"]')
print(f"Found {len(image_elements)} images on the page.")

Found 196 images on the page.

We have to extract the image url,name tags,like and comment on each image

In [5]:
# STEP 3:- Scraping the image details
# image url, name tags, likes and comments on each image
image_data = []
for sp in soup.find_all('div', class_='container'):
    img = sp.find('img')
    
    # 1. Safely check if img exists AND has a src attribute before proceeding
    if img and img.get('src') and 'gif' not in img.get('src'):
        link = img.get('src')
        
        # 2. Safely extract tags (Default to empty string if missing)
        tags_div = sp.find('div', class_='tags')
        tags_text = ""
        if tags_div:
            # Assuming the first 7 chars were something like "Tags: "
            # A safer way is replacing the specific word, or just matching words
            raw_tags = tags_div.text[7:].strip().split(' ')
            tags_text = ' '.join(list(set(raw_tags)))
        
        # 3. Safely extract likes and comments (Default to 0 if missing)
        likes, comments = 0, 0
        likes_comments_div = sp.find('div', class_='likes-comments')
        
        if likes_comments_div:
            spans = likes_comments_div.find_all('span')
            
            # re.search(r'\d+', text) finds the first sequence of numbers in a string
            if len(spans) > 0:
                likes_match = re.search(r'\d+', spans[0].text)
                likes = int(likes_match.group()) if likes_match else 0
                
            if len(spans) > 1:
                comments_match = re.search(r'\d+', spans[1].text)
                comments = int(comments_match.group()) if comments_match else 0
        
        image_data.append([link, tags_text, likes, comments])

In [6]:
# STEP 4: Make in to a dataframe
df = pd.DataFrame(image_data, columns=['Image URL', 'Tags', 'Likes', 'Comments'])

In [7]:
df

,Image URL,Tags,Likes,Comments
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Sky Clouds, Blue Atmosphere,",196,55
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Hummingbird Ornithology, Bird,",76,20
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainbow, Sea, Rainfall,",282,106
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Cherry Blossoms, Japan, Road, Sakura",42,11
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Marguerite, Flower, Cape Plant",39,15
...,...,...,...,...
191,https://cdn.pixabay.com/photo/2022/03/31/14/16...,"Bee, Pollination, Entomology, Macro",57,41
192,https://cdn.pixabay.com/photo/2022/04/06/05/26...,"Meadow Aurora Butterfly,",25,16
193,https://cdn.pixabay.com/photo/2021/12/02/13/02...,Weihnachtskerzen 4,70,24
194,https://cdn.pixabay.com/photo/2022/04/06/14/27...,description a (optional) Add,40,33
195,https://cdn.pixabay.com/photo/2022/04/09/06/20...,"Flowering, Spring, Flower Tulip,",9,2

In [8]:
# STEP 5: Close the Selenium WebDriver
driver.quit()

In [9]:
# STEP 6: Save the data to an Excel file
df.to_excel("stock_images_data.xlsx", index=False)

In [10]:
# STEP 7: Download the images to a local folder
# Create a folder to save the images
path=[]
os.makedirs("downloaded_images", exist_ok=True)
# Use a browser-like User-Agent to avoid being blocked by the server
download_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Safari/537.36"
}
# Download each image
for index, row in tqdm(df.iterrows(), total=len(df)):
    image_url = row['Image URL']
    if image_url.startswith('/'):
        image_url = urljoin("https://stock-pictures.netlify.app/", image_url)
    image_name = f"image_{index + 1}.jpg"
    save_path = os.path.join("downloaded_images", image_name)
    path.append(save_path)
    try:
        response = requests.get(image_url, headers=download_headers, timeout=30, stream=True)
        response.raise_for_status()
        with open(save_path, "wb") as f:
            for chunk in response.iter_content(chunk_size=10240):
                if chunk:
                    f.write(chunk)
        print(f"Downloaded: {image_name}")
    except Exception as e:
        print(f"Failed to download {image_name}: {image_url} : {e}")

  0%|          | 0/196 [00:00<?, ?it/s]

  1%|          | 1/196 [00:00<03:03,  1.06it/s]

Downloaded: image_1.jpg

  1%|          | 2/196 [00:02<03:18,  1.03s/it]

Downloaded: image_2.jpg

  2%|▏         | 3/196 [00:02<03:01,  1.06it/s]

Downloaded: image_3.jpg

  2%|▏         | 4/196 [00:03<02:43,  1.18it/s]

Downloaded: image_4.jpg

  3%|▎         | 5/196 [00:04<02:33,  1.24it/s]

Downloaded: image_5.jpg

  3%|▎         | 6/196 [00:05<02:30,  1.26it/s]

Downloaded: image_6.jpg

  4%|▎         | 7/196 [00:05<02:21,  1.33it/s]

Downloaded: image_7.jpg

  4%|▍         | 8/196 [00:06<02:08,  1.46it/s]

Downloaded: image_8.jpg

  5%|▍         | 9/196 [00:06<02:02,  1.53it/s]

Downloaded: image_9.jpg

  5%|▌         | 10/196 [00:07<01:57,  1.58it/s]

Downloaded: image_10.jpg

  6%|▌         | 11/196 [00:08<01:53,  1.63it/s]

Downloaded: image_11.jpg

  6%|▌         | 12/196 [00:08<01:49,  1.67it/s]

Downloaded: image_12.jpg

  7%|▋         | 13/196 [00:09<01:47,  1.71it/s]

Downloaded: image_13.jpg

  7%|▋         | 14/196 [00:09<01:46,  1.70it/s]

Downloaded: image_14.jpg

  8%|▊         | 15/196 [00:10<01:45,  1.71it/s]

Downloaded: image_15.jpg

  8%|▊         | 16/196 [00:10<01:45,  1.71it/s]

Downloaded: image_16.jpg

  9%|▊         | 17/196 [00:12<02:17,  1.30it/s]

Downloaded: image_17.jpg

  9%|▉         | 18/196 [00:12<02:05,  1.42it/s]

Downloaded: image_18.jpg

 10%|▉         | 19/196 [00:13<01:57,  1.50it/s]

Downloaded: image_19.jpg

 10%|█         | 20/196 [00:13<01:51,  1.58it/s]

Downloaded: image_20.jpg

 11%|█         | 21/196 [00:14<01:46,  1.64it/s]

Downloaded: image_21.jpg

 11%|█         | 22/196 [00:14<01:43,  1.69it/s]

Downloaded: image_22.jpg

 12%|█▏        | 23/196 [00:15<01:52,  1.54it/s]

Downloaded: image_23.jpg

 12%|█▏        | 24/196 [00:16<02:11,  1.31it/s]

Downloaded: image_24.jpg

 13%|█▎        | 25/196 [00:17<02:16,  1.25it/s]

Downloaded: image_25.jpg

 13%|█▎        | 26/196 [00:18<02:09,  1.31it/s]

Downloaded: image_26.jpg

 14%|█▍        | 27/196 [00:18<02:06,  1.33it/s]

Downloaded: image_27.jpg

 14%|█▍        | 28/196 [00:19<02:00,  1.40it/s]

Downloaded: image_28.jpg

 15%|█▍        | 29/196 [00:20<01:50,  1.51it/s]

Downloaded: image_29.jpg

 15%|█▌        | 30/196 [00:20<01:45,  1.57it/s]

Downloaded: image_30.jpg

 16%|█▌        | 31/196 [00:21<01:44,  1.58it/s]

Downloaded: image_31.jpg

 16%|█▋        | 32/196 [00:22<02:13,  1.23it/s]

Failed to download image_32.jpg: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg : 403 Client Error: Forbidden for url: https://cdn.pixabay.com/photo/2022/02/27/19/46/tourist-attraction-7037967__340.jpg

 17%|█▋        | 33/196 [00:23<02:01,  1.35it/s]

Downloaded: image_33.jpg

 17%|█▋        | 34/196 [00:23<01:52,  1.45it/s]

Downloaded: image_34.jpg

 18%|█▊        | 35/196 [00:24<01:44,  1.54it/s]

Downloaded: image_35.jpg

 18%|█▊        | 36/196 [00:24<01:38,  1.62it/s]

Downloaded: image_36.jpg

 19%|█▉        | 37/196 [00:25<01:35,  1.67it/s]

Downloaded: image_37.jpg

 19%|█▉        | 38/196 [00:25<01:32,  1.71it/s]

Downloaded: image_38.jpg

 20%|█▉        | 39/196 [00:26<01:30,  1.73it/s]

Downloaded: image_39.jpg

 20%|██        | 40/196 [00:27<01:28,  1.75it/s]

Downloaded: image_40.jpg

 21%|██        | 41/196 [00:27<01:28,  1.75it/s]

Downloaded: image_41.jpg

 21%|██▏       | 42/196 [00:28<01:28,  1.74it/s]

Downloaded: image_42.jpg

 22%|██▏       | 43/196 [00:28<01:27,  1.75it/s]

Downloaded: image_43.jpg

 22%|██▏       | 44/196 [00:29<01:26,  1.75it/s]

Downloaded: image_44.jpg

 23%|██▎       | 45/196 [00:29<01:26,  1.75it/s]

Downloaded: image_45.jpg

 23%|██▎       | 46/196 [00:30<01:36,  1.56it/s]

Downloaded: image_46.jpg

 24%|██▍       | 47/196 [00:31<01:45,  1.41it/s]

Downloaded: image_47.jpg

 24%|██▍       | 48/196 [00:32<01:51,  1.32it/s]

Downloaded: image_48.jpg

 25%|██▌       | 49/196 [00:33<01:49,  1.34it/s]

Downloaded: image_49.jpg

 26%|██▌       | 50/196 [00:33<01:45,  1.38it/s]

Downloaded: image_50.jpg

 26%|██▌       | 51/196 [00:34<01:41,  1.43it/s]

Downloaded: image_51.jpg

 27%|██▋       | 52/196 [00:35<01:35,  1.50it/s]

Downloaded: image_52.jpg

 27%|██▋       | 53/196 [00:35<01:30,  1.58it/s]

Downloaded: image_53.jpg

 28%|██▊       | 54/196 [00:36<01:25,  1.65it/s]

Downloaded: image_54.jpg

 28%|██▊       | 55/196 [00:36<01:22,  1.70it/s]

Downloaded: image_55.jpg

 29%|██▊       | 56/196 [00:37<01:20,  1.73it/s]

Downloaded: image_56.jpg

 29%|██▉       | 57/196 [00:37<01:19,  1.75it/s]

Downloaded: image_57.jpg

 30%|██▉       | 58/196 [00:38<01:17,  1.77it/s]

Downloaded: image_58.jpg

 30%|███       | 59/196 [00:38<01:16,  1.78it/s]

Downloaded: image_59.jpg

 31%|███       | 60/196 [00:39<01:16,  1.78it/s]

Downloaded: image_60.jpg

 31%|███       | 61/196 [00:40<01:15,  1.78it/s]

Downloaded: image_61.jpg

 32%|███▏      | 62/196 [00:40<01:15,  1.77it/s]

Downloaded: image_62.jpg

 32%|███▏      | 63/196 [00:41<01:13,  1.80it/s]

Downloaded: image_63.jpg

 33%|███▎      | 64/196 [00:41<01:12,  1.82it/s]

Downloaded: image_64.jpg

 33%|███▎      | 65/196 [00:42<01:11,  1.83it/s]

Downloaded: image_65.jpg

 34%|███▎      | 66/196 [00:42<01:11,  1.81it/s]

Downloaded: image_66.jpg

 34%|███▍      | 67/196 [00:43<01:11,  1.80it/s]

Downloaded: image_67.jpg

 35%|███▍      | 68/196 [00:43<01:11,  1.80it/s]

Downloaded: image_68.jpg

 35%|███▌      | 69/196 [00:44<01:11,  1.78it/s]

Downloaded: image_69.jpg

 36%|███▌      | 70/196 [00:45<01:11,  1.77it/s]

Downloaded: image_70.jpg

 36%|███▌      | 71/196 [00:45<01:14,  1.69it/s]

Downloaded: image_71.jpg

 37%|███▋      | 72/196 [00:46<01:20,  1.54it/s]

Downloaded: image_72.jpg

 37%|███▋      | 73/196 [00:47<01:27,  1.40it/s]

Downloaded: image_73.jpg

 38%|███▊      | 74/196 [00:48<01:25,  1.42it/s]

Downloaded: image_74.jpg

 38%|███▊      | 75/196 [00:48<01:24,  1.44it/s]

Downloaded: image_75.jpg

 39%|███▉      | 76/196 [00:49<01:20,  1.49it/s]

Downloaded: image_76.jpg

 39%|███▉      | 77/196 [00:49<01:16,  1.55it/s]

Downloaded: image_77.jpg

 40%|███▉      | 78/196 [00:50<01:12,  1.62it/s]

Downloaded: image_78.jpg

 40%|████      | 79/196 [00:51<01:11,  1.64it/s]

Downloaded: image_79.jpg

 41%|████      | 80/196 [00:51<01:09,  1.67it/s]

Downloaded: image_80.jpg

 41%|████▏     | 81/196 [00:52<01:08,  1.69it/s]

Downloaded: image_81.jpg

 42%|████▏     | 82/196 [00:52<01:06,  1.72it/s]

Downloaded: image_82.jpg

 42%|████▏     | 83/196 [00:53<01:04,  1.75it/s]

Downloaded: image_83.jpg

 43%|████▎     | 84/196 [00:53<01:03,  1.77it/s]

Downloaded: image_84.jpg

 43%|████▎     | 85/196 [00:54<01:02,  1.78it/s]

Downloaded: image_85.jpg

 44%|████▍     | 86/196 [00:54<01:01,  1.79it/s]

Downloaded: image_86.jpg

 44%|████▍     | 87/196 [00:55<01:00,  1.82it/s]

Downloaded: image_87.jpg

 45%|████▍     | 88/196 [00:56<01:01,  1.75it/s]

Downloaded: image_88.jpg

 45%|████▌     | 89/196 [00:56<01:02,  1.70it/s]

Downloaded: image_89.jpg

 46%|████▌     | 90/196 [00:57<01:02,  1.70it/s]

Downloaded: image_90.jpg

 46%|████▋     | 91/196 [00:57<01:02,  1.69it/s]

Downloaded: image_91.jpg

 47%|████▋     | 92/196 [00:58<01:02,  1.67it/s]

Downloaded: image_92.jpg

 47%|████▋     | 93/196 [00:59<01:03,  1.63it/s]

Downloaded: image_93.jpg

 48%|████▊     | 94/196 [00:59<01:06,  1.53it/s]

Downloaded: image_94.jpg

 48%|████▊     | 95/196 [01:00<01:08,  1.48it/s]

Downloaded: image_95.jpg

 49%|████▉     | 96/196 [01:01<01:15,  1.32it/s]

Downloaded: image_96.jpg

 49%|████▉     | 97/196 [01:02<01:29,  1.11it/s]

Downloaded: image_97.jpg

 50%|█████     | 98/196 [01:04<01:36,  1.01it/s]

Downloaded: image_98.jpg

 51%|█████     | 99/196 [01:04<01:30,  1.07it/s]

Downloaded: image_99.jpg

 51%|█████     | 100/196 [01:05<01:25,  1.12it/s]

Downloaded: image_100.jpg

 52%|█████▏    | 101/196 [01:06<01:22,  1.15it/s]

Downloaded: image_101.jpg

 52%|█████▏    | 102/196 [01:07<01:18,  1.20it/s]

Downloaded: image_102.jpg

 53%|█████▎    | 103/196 [01:07<01:13,  1.26it/s]

Downloaded: image_103.jpg

 53%|█████▎    | 104/196 [01:08<01:11,  1.28it/s]

Downloaded: image_104.jpg

 54%|█████▎    | 105/196 [01:09<01:08,  1.32it/s]

Downloaded: image_105.jpg

 54%|█████▍    | 106/196 [01:09<01:04,  1.40it/s]

Downloaded: image_106.jpg

 55%|█████▍    | 107/196 [01:10<01:00,  1.48it/s]

Downloaded: image_107.jpg

 55%|█████▌    | 108/196 [01:11<00:57,  1.52it/s]

Downloaded: image_108.jpg

 56%|█████▌    | 109/196 [01:11<00:56,  1.55it/s]

Downloaded: image_109.jpg

 56%|█████▌    | 110/196 [01:12<00:54,  1.58it/s]

Downloaded: image_110.jpg

 57%|█████▋    | 111/196 [01:12<00:51,  1.64it/s]

Downloaded: image_111.jpg

 57%|█████▋    | 112/196 [01:13<00:50,  1.68it/s]

Downloaded: image_112.jpg

 58%|█████▊    | 113/196 [01:14<00:50,  1.66it/s]

Downloaded: image_113.jpg

 58%|█████▊    | 114/196 [01:14<00:50,  1.61it/s]

Downloaded: image_114.jpg

 59%|█████▊    | 115/196 [01:15<00:51,  1.58it/s]

Downloaded: image_115.jpg

 59%|█████▉    | 116/196 [01:16<00:50,  1.60it/s]

Downloaded: image_116.jpg

 60%|█████▉    | 117/196 [01:17<00:56,  1.39it/s]

Downloaded: image_117.jpg

 60%|██████    | 118/196 [01:18<01:02,  1.25it/s]

Downloaded: image_118.jpg

 61%|██████    | 119/196 [01:18<01:00,  1.28it/s]

Downloaded: image_119.jpg

 61%|██████    | 120/196 [01:19<00:56,  1.35it/s]

Downloaded: image_120.jpg

 62%|██████▏   | 121/196 [01:20<00:53,  1.41it/s]

Downloaded: image_121.jpg

 62%|██████▏   | 122/196 [01:21<01:03,  1.16it/s]

Downloaded: image_122.jpg

 63%|██████▎   | 123/196 [01:21<00:59,  1.24it/s]

Downloaded: image_123.jpg

 63%|██████▎   | 124/196 [01:22<00:54,  1.33it/s]

Downloaded: image_124.jpg

 64%|██████▍   | 125/196 [01:23<00:49,  1.44it/s]

Downloaded: image_125.jpg

 64%|██████▍   | 126/196 [01:23<00:45,  1.53it/s]

Downloaded: image_126.jpg

 65%|██████▍   | 127/196 [01:24<00:42,  1.62it/s]

Downloaded: image_127.jpg

 65%|██████▌   | 128/196 [01:24<00:40,  1.68it/s]

Downloaded: image_128.jpg

 66%|██████▌   | 129/196 [01:25<00:38,  1.74it/s]

Downloaded: image_129.jpg

 66%|██████▋   | 130/196 [01:25<00:37,  1.75it/s]

Downloaded: image_130.jpg

 67%|██████▋   | 131/196 [01:26<00:36,  1.77it/s]

Downloaded: image_131.jpg

 67%|██████▋   | 132/196 [01:26<00:36,  1.78it/s]

Downloaded: image_132.jpg

 68%|██████▊   | 133/196 [01:27<00:35,  1.77it/s]

Downloaded: image_133.jpg

 68%|██████▊   | 134/196 [01:28<00:34,  1.79it/s]

Downloaded: image_134.jpg

 69%|██████▉   | 135/196 [01:28<00:34,  1.79it/s]

Downloaded: image_135.jpg

 69%|██████▉   | 136/196 [01:29<00:33,  1.81it/s]

Downloaded: image_136.jpg

 70%|██████▉   | 137/196 [01:29<00:32,  1.80it/s]

Downloaded: image_137.jpg

 70%|███████   | 138/196 [01:30<00:31,  1.82it/s]

Downloaded: image_138.jpg

 71%|███████   | 139/196 [01:30<00:32,  1.76it/s]

Downloaded: image_139.jpg

 71%|███████▏  | 140/196 [01:31<00:36,  1.52it/s]

Downloaded: image_140.jpg

 72%|███████▏  | 141/196 [01:32<00:41,  1.34it/s]

Downloaded: image_141.jpg

 72%|███████▏  | 142/196 [01:34<00:52,  1.03it/s]

Downloaded: image_142.jpg

 73%|███████▎  | 143/196 [01:34<00:46,  1.14it/s]

Downloaded: image_143.jpg

 73%|███████▎  | 144/196 [01:35<00:41,  1.27it/s]

Downloaded: image_144.jpg

 74%|███████▍  | 145/196 [01:35<00:36,  1.40it/s]

Downloaded: image_145.jpg

 74%|███████▍  | 146/196 [01:36<00:33,  1.51it/s]

Downloaded: image_146.jpg

 75%|███████▌  | 147/196 [01:37<00:30,  1.59it/s]

Downloaded: image_147.jpg

 76%|███████▌  | 148/196 [01:37<00:29,  1.64it/s]

Downloaded: image_148.jpg

 76%|███████▌  | 149/196 [01:38<00:28,  1.64it/s]

Downloaded: image_149.jpg

 77%|███████▋  | 150/196 [01:38<00:27,  1.69it/s]

Downloaded: image_150.jpg

 77%|███████▋  | 151/196 [01:39<00:26,  1.73it/s]

Downloaded: image_151.jpg

 78%|███████▊  | 152/196 [01:39<00:24,  1.76it/s]

Downloaded: image_152.jpg

 78%|███████▊  | 153/196 [01:40<00:24,  1.78it/s]

Downloaded: image_153.jpg

 79%|███████▊  | 154/196 [01:40<00:23,  1.80it/s]

Downloaded: image_154.jpg

 79%|███████▉  | 155/196 [01:41<00:22,  1.80it/s]

Downloaded: image_155.jpg

 80%|███████▉  | 156/196 [01:42<00:22,  1.82it/s]

Downloaded: image_156.jpg

 80%|████████  | 157/196 [01:42<00:21,  1.81it/s]

Downloaded: image_157.jpg

 81%|████████  | 158/196 [01:43<00:22,  1.67it/s]

Downloaded: image_158.jpg

 81%|████████  | 159/196 [01:43<00:22,  1.61it/s]

Downloaded: image_159.jpg

 82%|████████▏ | 160/196 [01:44<00:23,  1.57it/s]

Downloaded: image_160.jpg

 82%|████████▏ | 161/196 [01:46<00:29,  1.18it/s]

Downloaded: image_161.jpg

 83%|████████▎ | 162/196 [01:46<00:29,  1.16it/s]

Downloaded: image_162.jpg

 83%|████████▎ | 163/196 [01:47<00:29,  1.12it/s]

Downloaded: image_163.jpg

 84%|████████▎ | 164/196 [01:48<00:28,  1.13it/s]

Downloaded: image_164.jpg

 84%|████████▍ | 165/196 [01:49<00:25,  1.21it/s]

Downloaded: image_165.jpg

 85%|████████▍ | 166/196 [01:50<00:24,  1.24it/s]

Downloaded: image_166.jpg

 85%|████████▌ | 167/196 [01:50<00:22,  1.31it/s]

Downloaded: image_167.jpg

 86%|████████▌ | 168/196 [01:51<00:19,  1.41it/s]

Downloaded: image_168.jpg

 86%|████████▌ | 169/196 [01:51<00:17,  1.51it/s]

Downloaded: image_169.jpg

 87%|████████▋ | 170/196 [01:52<00:16,  1.60it/s]

Downloaded: image_170.jpg

 87%|████████▋ | 171/196 [01:53<00:15,  1.66it/s]

Downloaded: image_171.jpg

 88%|████████▊ | 172/196 [01:53<00:14,  1.71it/s]

Downloaded: image_172.jpg

 88%|████████▊ | 173/196 [01:54<00:13,  1.76it/s]

Downloaded: image_173.jpg

 89%|████████▉ | 174/196 [01:54<00:12,  1.79it/s]

Downloaded: image_174.jpg

 89%|████████▉ | 175/196 [01:55<00:11,  1.79it/s]

Downloaded: image_175.jpg

 90%|████████▉ | 176/196 [01:55<00:11,  1.80it/s]

Downloaded: image_176.jpg

 90%|█████████ | 177/196 [01:56<00:10,  1.78it/s]

Downloaded: image_177.jpg

 91%|█████████ | 178/196 [01:57<00:13,  1.33it/s]

Downloaded: image_178.jpg

 91%|█████████▏| 179/196 [01:58<00:11,  1.45it/s]

Downloaded: image_179.jpg

 92%|█████████▏| 180/196 [01:58<00:10,  1.53it/s]

Downloaded: image_180.jpg

 92%|█████████▏| 181/196 [01:59<00:09,  1.61it/s]

Downloaded: image_181.jpg

 93%|█████████▎| 182/196 [01:59<00:08,  1.67it/s]

Downloaded: image_182.jpg

 93%|█████████▎| 183/196 [02:00<00:07,  1.73it/s]

Downloaded: image_183.jpg

 94%|█████████▍| 184/196 [02:00<00:06,  1.75it/s]

Downloaded: image_184.jpg

 94%|█████████▍| 185/196 [02:01<00:06,  1.77it/s]

Downloaded: image_185.jpg

 95%|█████████▍| 186/196 [02:01<00:05,  1.78it/s]

Downloaded: image_186.jpg

 95%|█████████▌| 187/196 [02:02<00:05,  1.62it/s]

Downloaded: image_187.jpg

 96%|█████████▌| 188/196 [02:03<00:05,  1.44it/s]

Downloaded: image_188.jpg

 96%|█████████▋| 189/196 [02:04<00:05,  1.38it/s]

Downloaded: image_189.jpg

 97%|█████████▋| 190/196 [02:05<00:04,  1.42it/s]

Downloaded: image_190.jpg

 97%|█████████▋| 191/196 [02:05<00:03,  1.48it/s]

Downloaded: image_191.jpg

 98%|█████████▊| 192/196 [02:06<00:02,  1.53it/s]

Downloaded: image_192.jpg

 98%|█████████▊| 193/196 [02:06<00:01,  1.59it/s]

Downloaded: image_193.jpg

 99%|█████████▉| 194/196 [02:07<00:01,  1.65it/s]

Downloaded: image_194.jpg

 99%|█████████▉| 195/196 [02:07<00:00,  1.70it/s]

Downloaded: image_195.jpg

100%|██████████| 196/196 [02:08<00:00,  1.53it/s]

Downloaded: image_196.jpg

In [11]:
# STEP 8: Update the Excel file with the local image paths
df['Local Image Path'] = path
df.to_excel("stock_images_data.xlsx", index=False)

In [12]:
df

,Image URL,Tags,Likes,Comments,Local Image Path
0,https://cdn.pixabay.com/photo/2022/03/06/05/30...,"Sky, Sky Clouds, Blue Atmosphere,",196,55,downloaded_images\image_1.jpg
1,https://cdn.pixabay.com/photo/2022/04/07/11/45...,"Hummingbird Ornithology, Bird,",76,20,downloaded_images\image_2.jpg
2,https://cdn.pixabay.com/photo/2022/02/28/15/28...,"Subtropical Rainbow, Sea, Rainfall,",282,106,downloaded_images\image_3.jpg
3,https://cdn.pixabay.com/photo/2022/04/04/02/52...,"Cherry Blossoms, Japan, Road, Sakura",42,11,downloaded_images\image_4.jpg
4,https://cdn.pixabay.com/photo/2022/04/09/18/06...,"Marguerite, Flower, Cape Plant",39,15,downloaded_images\image_5.jpg
...,...,...,...,...,...
191,https://cdn.pixabay.com/photo/2022/03/31/14/16...,"Bee, Pollination, Entomology, Macro",57,41,downloaded_images\image_192.jpg
192,https://cdn.pixabay.com/photo/2022/04/06/05/26...,"Meadow Aurora Butterfly,",25,16,downloaded_images\image_193.jpg
193,https://cdn.pixabay.com/photo/2021/12/02/13/02...,Weihnachtskerzen 4,70,24,downloaded_images\image_194.jpg
194,https://cdn.pixabay.com/photo/2022/04/06/14/27...,description a (optional) Add,40,33,downloaded_images\image_195.jpg
195,https://cdn.pixabay.com/photo/2022/04/09/06/20...,"Flowering, Spring, Flower Tulip,",9,2,downloaded_images\image_196.jpg

In [14]:
# STEP 9: Clone the dataset
df_new = df.copy()
# two columns path and tags are there reset of the columns are removed
df_new = df_new[['Local Image Path', 'Tags']]
df_new.to_excel("stock_images_data_cloned.xlsx", index=False)
df_new

In [26]:
# STEP 10: Make the differnet folder for unque tags
# Get unique tags
unique_tags = set()
for tags in df_new['Tags']:
    unique_tags.update(tags.split())

# make a main folder to store the images in different folders based on tags
os.makedirs("tagged_images", exist_ok=True)

# Function to sanitize tag names for folder creation
def sanitize_tag(tag):
    tag = tag.strip()
    # remove common prefix like "Tags - " if present
    tag = re.sub(r'(?i)^tags\s*[-:]\s*', '', tag)
    # replace invalid filename chars with underscore
    tag = re.sub(r'[<>:"/\\|?*\n\r\t]', '_', tag)
    # replace commas and sequences of whitespace with underscore
    tag = re.sub(r'[,\s]+', '_', tag)
    # remove trailing dots/underscores/spaces
    tag = tag.rstrip('._ ')
    if not tag:
        tag = 'untitled'
    # avoid reserved Windows names
    if re.fullmatch(r'(?i)(con|prn|aux|nul|com[1-9]|lpt[1-9])', tag):
        tag = f'_{tag}'
        return tag

    # Create folders for each unique tag
    for tag in unique_tags:
        safe_tag = sanitize_tag(tag)
        tag_folder = os.path.join("tagged_images", safe_tag)
        os.makedirs(tag_folder, exist_ok=True)